;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 09/09/2020 17:40:35
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2B72			GOTO	_main
$048B	$	_mul_32x32_u:
$048B	$1303			BCF	STATUS, RP1
$048C	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$048D	$3022			MOVLW	34
;math.ppas,1579 :: 		
$048E	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$048F	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0490	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0491	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0492	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$0493	$	_NEXT:
;math.ppas,1589 :: 		
$0493	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$0494	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0495	$2CC1			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0496	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0497	$	_LOOP:
;math.ppas,1603 :: 		
$0497	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$0498	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0499	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$049A	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$049B	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$049C	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$049D	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$049E	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$049F	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$04A0	$2C93			GOTO	_NEXT
;math.ppas,1617 :: 		
$04A1	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$04A2	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$04A3	$2CB3			GOTO	_EXIT1
;math.ppas,1626 :: 		
$04A4	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$04A5	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$04A6	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$04A7	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$04A8	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$04A9	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$04AA	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$04AB	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$04AC	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$04AD	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$04AE	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$04AF	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$04B0	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$04B1	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$04B2	$2C97			GOTO	_LOOP
;math.ppas,1647 :: 		
$04B3	$	_EXIT1:
;math.ppas,1648 :: 		
$04B3	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$04B4	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$04B5	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$04B6	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$04B7	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$04B8	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$04B9	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$04BA	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$04BB	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$04BC	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$04BD	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$04BE	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$04BF	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$04C0	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$04C1	$	_EXIT2:
;math.ppas,1665 :: 		
$04C1	$	math_L_13:
;math.ppas,1666 :: 		
$04C1	$0008			RETURN
$0004	$	_sdiv3232l:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0006	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0007	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0008	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0009	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$000A	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$000B	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$000C	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$000D	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$000E	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$000F	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0010	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0011	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0012	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0013	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0014	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0015	$3007			MOVLW	7
;math.ppas,559 :: 		
$0016	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0017	$	LOOPS3232A:
;math.ppas,561 :: 		
$0017	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0018	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0019	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$001A	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$001B	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$001C	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$001D	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$001E	$282D			GOTO	SADD22LA
;math.ppas,570 :: 		
$001F	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0020	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0021	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0022	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0023	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0024	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0025	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0026	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0027	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0028	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0029	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$002A	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$002B	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$002C	$283A			GOTO	SOK22LA
;math.ppas,585 :: 		
$002D	$	SADD22LA:
;math.ppas,586 :: 		
$002D	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$002E	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$002F	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0030	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0031	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0032	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0033	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0034	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0035	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0036	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0037	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0038	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0039	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$003A	$	SOK22LA:
;math.ppas,602 :: 		
$003A	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$003B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$003C	$2817			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$003D	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$003E	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$003F	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0040	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0041	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0042	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0043	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0044	$2853			GOTO	SADD22L8
;math.ppas,615 :: 		
$0045	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0046	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0047	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0048	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0049	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$004A	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$004B	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$004C	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$004D	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$004E	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$004F	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0050	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0051	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0052	$2860			GOTO	SOK22L8
;math.ppas,630 :: 		
$0053	$	SADD22L8:
;math.ppas,631 :: 		
$0053	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0054	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0055	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0056	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0057	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0058	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0059	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$005A	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$005B	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$005C	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$005D	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$005E	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$005F	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0060	$	SOK22L8:
;math.ppas,647 :: 		
$0060	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0061	$3007			MOVLW	7
;math.ppas,650 :: 		
$0062	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0063	$	LOOPS3232B:
;math.ppas,652 :: 		
$0063	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0064	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0065	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0066	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0067	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0068	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0069	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$006A	$2879			GOTO	SADD22LB
;math.ppas,661 :: 		
$006B	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$006C	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$006D	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$006E	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$006F	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0070	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0071	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0072	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0073	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0074	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0075	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0076	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0077	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0078	$2886			GOTO	SOK22LB
;math.ppas,676 :: 		
$0079	$	SADD22LB:
;math.ppas,677 :: 		
$0079	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$007A	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$007B	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$007C	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$007D	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$007E	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$007F	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0080	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0081	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0082	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0083	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0084	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0085	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0086	$	SOK22LB:
;math.ppas,693 :: 		
$0086	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0087	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0088	$2863			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$0089	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$008A	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$008B	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$008C	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$008D	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$008E	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$008F	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0090	$289F			GOTO	SADD22L16
;math.ppas,706 :: 		
$0091	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0092	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0093	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0094	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0095	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0096	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0097	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0098	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0099	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$009A	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$009B	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$009C	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$009D	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$009E	$28AC			GOTO	SOK22L16
;math.ppas,721 :: 		
$009F	$	SADD22L16:
;math.ppas,722 :: 		
$009F	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$00A0	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$00A1	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$00A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$00A3	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$00A4	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$00A5	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$00A6	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$00A7	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$00A8	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$00A9	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$00AA	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$00AB	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$00AC	$	SOK22L16:
;math.ppas,738 :: 		
$00AC	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$00AD	$3007			MOVLW	7
;math.ppas,741 :: 		
$00AE	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$00AF	$	LOOPS3232C:
;math.ppas,743 :: 		
$00AF	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$00B0	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$00B1	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$00B2	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$00B3	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$00B4	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$00B5	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$00B6	$28C5			GOTO	SADD22LC
;math.ppas,752 :: 		
$00B7	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$00B8	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$00B9	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$00BA	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$00BB	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$00BC	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$00BD	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$00BE	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$00BF	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$00C0	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$00C1	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$00C2	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$00C3	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$00C4	$28D2			GOTO	SOK22LC
;math.ppas,767 :: 		
$00C5	$	SADD22LC:
;math.ppas,768 :: 		
$00C5	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$00C6	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$00C7	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$00C8	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$00C9	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$00CA	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$00CB	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$00CC	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$00CD	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$00CE	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$00CF	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$00D0	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$00D1	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$00D2	$	SOK22LC:
;math.ppas,784 :: 		
$00D2	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$00D3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$00D4	$28AF			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$00D5	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$00D6	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$00D7	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$00D8	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$00D9	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$00DA	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$00DB	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$00DC	$28EB			GOTO	SADD22L24
;math.ppas,797 :: 		
$00DD	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$00DE	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$00DF	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$00E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$00E1	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$00E2	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$00E3	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$00E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$00E5	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$00E6	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$00E7	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$00E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$00E9	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$00EA	$28F8			GOTO	SOK22L24
;math.ppas,812 :: 		
$00EB	$	SADD22L24:
;math.ppas,813 :: 		
$00EB	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$00EC	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$00ED	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$00EE	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$00EF	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$00F0	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$00F1	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$00F2	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$00F3	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$00F4	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$00F5	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$00F6	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$00F7	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$00F8	$	SOK22L24:
;math.ppas,829 :: 		
$00F8	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$00F9	$3007			MOVLW	7
;math.ppas,832 :: 		
$00FA	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$00FB	$	LOOPS3232D:
;math.ppas,834 :: 		
$00FB	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$00FC	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$00FD	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$00FE	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$00FF	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0100	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0101	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0102	$2911			GOTO	SADD22LD
;math.ppas,843 :: 		
$0103	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0104	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0105	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0106	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0107	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0108	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0109	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$010A	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$010B	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$010C	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$010D	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$010E	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$010F	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0110	$291E			GOTO	SOK22LD
;math.ppas,858 :: 		
$0111	$	SADD22LD:
;math.ppas,859 :: 		
$0111	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0112	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0113	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0114	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0115	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0116	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0117	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0118	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0119	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$011A	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$011B	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$011C	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$011D	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$011E	$	SOK22LD:
;math.ppas,876 :: 		
$011E	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$011F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0120	$28FB			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0121	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0122	$2931			GOTO	SOK22L
;math.ppas,882 :: 		
$0123	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0124	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0125	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0126	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0127	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0128	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0129	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$012A	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$012B	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$012C	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$012D	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$012E	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$012F	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0130	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0131	$	SOK22L:
;math.ppas,897 :: 		
$0131	$	math_L_9:
;math.ppas,898 :: 		
$0131	$0008			RETURN
$0507	$	_comfrem:
$0507	$1303			BCF	STATUS, RP1
$0508	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0509	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$050A	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$050B	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$050C	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$050D	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$050E	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$050F	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0510	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0511	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0512	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0513	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0514	$	math_L_10:
;math.ppas,915 :: 		
$0514	$0008			RETURN
$0515	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0515	$1303			BCF	STATUS, RP1
$0516	$1283			BCF	STATUS, RP0
$0517	$080C			MOVF	PIR1, 0
$0518	$00F1			MOVWF	STACK_1
$0519	$3000			MOVLW	0
$051A	$1AF1			BTFSC	STACK_1, 5
$051B	$3001			MOVLW	1
$051C	$00F1			MOVWF	STACK_1
$051D	$0871			MOVF	STACK_1, 0
$051E	$00C7			MOVWF	_usart_data_ready_local_result
$051F	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$051F	$0847			MOVF	_usart_data_ready_local_result, 0
$0520	$00F0			MOVWF	STACK_0
$0521	$0008			RETURN
$04F4	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$04F4	$1303			BCF	STATUS, RP1
$04F5	$1283			BCF	STATUS, RP0
$04F6	$081A			MOVF	RCREG, 0
$04F7	$00C7			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$04F8	$0818			MOVF	RCSTA, 0
$04F9	$00F1			MOVWF	STACK_1
$04FA	$3000			MOVLW	0
$04FB	$18F1			BTFSC	STACK_1, 1
$04FC	$3001			MOVLW	1
$04FD	$00F1			MOVWF	STACK_1
$04FE	$0871			MOVF	STACK_1, 0
$04FF	$3A01			XORLW	1
$0500	$1D03			BTFSS	STATUS, Z
$0501	$2D04			GOTO	USART_b75_L_21
$0502	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0502	$1218			BCF	RCSTA, 4
$0503	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0503	$	USART_b75_L_25:
$0503	$1618			BSF	RCSTA, 4
$0504	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$0504	$	USART_b75_L_21:
$0504	$	USART_b75_L_22:
$0504	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$0504	$0847			MOVF	_usart_read_local_result, 0
$0505	$00F0			MOVWF	STACK_0
$0506	$0008			RETURN
$0450	$	_mul_32x32_s:
$0450	$1303			BCF	STATUS, RP1
$0451	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$0452	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$0453	$	_IF_FIRST:
;math.ppas,1684 :: 		
$0453	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$0454	$2C62			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0455	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0455	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0456	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0457	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0458	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0459	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$045A	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$045B	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$045C	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$045D	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$045E	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$045F	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$0460	$3081			MOVLW	129
;math.ppas,1711 :: 		
$0461	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$0462	$	_IF_SECOND:
;math.ppas,1715 :: 		
$0462	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$0463	$2C70			GOTO	_MULT
;math.ppas,1722 :: 		
$0464	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$0464	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0465	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0466	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0467	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0468	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0469	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$046A	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$046B	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$046C	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$046D	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$046E	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$046F	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$0470	$	_MULT:
;math.ppas,1744 :: 		
$0470	$248B			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$0471	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$0472	$2C8A			GOTO	_EXIT
;math.ppas,1755 :: 		
$0473	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$0474	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0475	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0476	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0477	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0478	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0479	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$047A	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$047B	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$047C	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$047D	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$047E	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$047F	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$0480	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$0481	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$0482	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$0483	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$0484	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0485	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0486	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0487	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0488	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0489	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$048A	$	_EXIT:
;math.ppas,1793 :: 		
$048A	$	math_L_14:
;math.ppas,1794 :: 		
$048A	$0008			RETURN
$04C2	$	_div_16x16_u:
$04C2	$1303			BCF	STATUS, RP1
$04C3	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$04C4	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$04C5	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$04C6	$3010			MOVLW	16
;math.ppas,113 :: 		
$04C7	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$04C8	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$04C9	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$04CA	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$04CB	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$04CC	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$04CD	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$04CE	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$04CF	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$04D0	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$04D1	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$04D2	$2CDA			GOTO	$+8
;math.ppas,125 :: 		
$04D3	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$04D4	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$04D5	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$04D6	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$04D7	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$04D8	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$04D9	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$04DA	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$04DB	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$04DC	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$04DD	$2CC8			GOTO	$-21
;math.ppas,136 :: 		
$04DE	$	math_L_3:
;math.ppas,137 :: 		
$04DE	$0008			RETURN
$01F4	$	_div_32x32_s:
$01F4	$1303			BCF	STATUS, RP1
$01F5	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$01F6	$	FXD3232S:
;math.ppas,929 :: 		
$01F6	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$01F7	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$01F8	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$01F9	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$01FA	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$01FB	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$01FC	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$01FD	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$01FE	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$01FF	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0200	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0201	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0202	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0203	$2A88			GOTO	END_ALL
;math.ppas,944 :: 		
$0204	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0205	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0206	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0207	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0208	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0209	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$020A	$2A16			GOTO	CA3232S
;math.ppas,955 :: 		
$020B	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$020C	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$020D	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$020E	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$020F	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0210	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0211	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0212	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0213	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0214	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0215	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0216	$	CA3232S:
;math.ppas,968 :: 		
$0216	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0217	$2A23			GOTO	C3232SX
;math.ppas,971 :: 		
$0218	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0219	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$021A	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$021B	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$021C	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$021D	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$021E	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$021F	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0220	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0221	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0222	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0223	$	C3232SX:
;math.ppas,984 :: 		
$0223	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0224	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0225	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0226	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0227	$2A44			GOTO	C3232SX1
;math.ppas,989 :: 		
$0228	$	C3232S:
;math.ppas,992 :: 		
$0228	$2004			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0229	$	C3232S2:
;math.ppas,996 :: 		
$0229	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$022A	$2A61			GOTO	C3232SX4
;math.ppas,998 :: 		
$022B	$	C3232SOK:
;math.ppas,999 :: 		
$022B	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$022C	$2A88			GOTO	END_ALL
;math.ppas,1001 :: 		
$022D	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$022E	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$022F	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0230	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0231	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0232	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0233	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0234	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0235	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0236	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0237	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0238	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0239	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$023A	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$023B	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$023C	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$023D	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$023E	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$023F	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0240	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0241	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0242	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0243	$2A88			GOTO	END_ALL
;math.ppas,1026 :: 		
$0244	$	C3232SX1:
;math.ppas,1027 :: 		
$0244	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0245	$2A5B			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0246	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0247	$2A55			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0248	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0249	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$024A	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$024B	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$024C	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$024D	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$024E	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$024F	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0250	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0251	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0252	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0253	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0254	$2A2B			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0255	$	C3232SX2:
;math.ppas,1045 :: 		
$0255	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0256	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0257	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0258	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0259	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$025A	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$025B	$	C3232SX3:
;math.ppas,1053 :: 		
$025B	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$025C	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$025D	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$025E	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$025F	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0260	$2A28			GOTO	C3232S
;math.ppas,1061 :: 		
$0261	$	C3232SX4:
;math.ppas,1062 :: 		
$0261	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0262	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0263	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0264	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0265	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0266	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0267	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0268	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0269	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$026A	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$026B	$2A2B			GOTO	C3232SOK
;math.ppas,1073 :: 		
$026C	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$026D	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$026E	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$026F	$2A2B			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0270	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0271	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0272	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0273	$2A2B			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0274	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0275	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0276	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0277	$2A2B			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0278	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0279	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$027A	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$027B	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$027C	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$027D	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$027E	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$027F	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0280	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0281	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0282	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0283	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0284	$2A2B			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0285	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0286	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0287	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0288	$	END_ALL:
;math.ppas,1102 :: 		
$0288	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0289	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$028A	$2A8C			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$028B	$2507			CALL	_comfrem
;math.ppas,1108 :: 		
$028C	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$028C	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$028D	$	math_L_11:
;math.ppas,1111 :: 		
$028D	$0008			RETURN
$028E	$	_vdelay_ms:
;delays.pbas,65 :: 		dim NumberOfCyc as dword
;delays.pbas,67 :: 		NumberOfCyc = Clock_kHz >> 2 ' this will be done by compiler, no asm will be genereated except that for assignment
$028E	$30E8			MOVLW	232
$028F	$1303			BCF	STATUS, RP1
$0290	$1283			BCF	STATUS, RP0
$0291	$00C9			MOVWF	_vdelay_ms_local_numberofcyc
$0292	$3003			MOVLW	3
$0293	$00CA			MOVWF	_vdelay_ms_local_numberofcyc+1
$0294	$01CB			CLRF	_vdelay_ms_local_numberofcyc+2
$0295	$01CC			CLRF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,68 :: 		NumberOfCyc = Time_ms * NumberOfCyc
$0296	$0847			MOVF	FARG_VDelay_ms, 0
$0297	$00F0			MOVWF	STACK_0
$0298	$0848			MOVF	FARG_VDelay_ms+1, 0
$0299	$00F1			MOVWF	STACK_0+1
$029A	$01F2			CLRF	STACK_0+2
$029B	$01F3			CLRF	STACK_0+3
$029C	$30E8			MOVLW	232
$029D	$00F4			MOVWF	STACK_4
$029E	$3003			MOVLW	3
$029F	$00F5			MOVWF	STACK_4+1
$02A0	$3000			MOVLW	0
$02A1	$00F6			MOVWF	STACK_4+2
$02A2	$3000			MOVLW	0
$02A3	$00F7			MOVWF	STACK_4+3
$02A4	$248B			CALL	_mul_32x32_u
$02A5	$0870			MOVF	STACK_0, 0
$02A6	$00C9			MOVWF	_vdelay_ms_local_numberofcyc
$02A7	$0871			MOVF	STACK_0+1, 0
$02A8	$00CA			MOVWF	_vdelay_ms_local_numberofcyc+1
$02A9	$0872			MOVF	STACK_0+2, 0
$02AA	$00CB			MOVWF	_vdelay_ms_local_numberofcyc+2
$02AB	$0873			MOVF	STACK_0+3, 0
$02AC	$00CC			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,69 :: 		if NumberOfCyc < 675 then
$02AD	$3000			MOVLW	0
$02AE	$0273			SUBWF	STACK_0+3, 0
$02AF	$1D03			BTFSS	STATUS, Z
$02B0	$2ABB			GOTO	L_VDelay_ms_0
$02B1	$3000			MOVLW	0
$02B2	$0272			SUBWF	STACK_0+2, 0
$02B3	$1D03			BTFSS	STATUS, Z
$02B4	$2ABB			GOTO	L_VDelay_ms_0
$02B5	$3002			MOVLW	2
$02B6	$0271			SUBWF	STACK_0+1, 0
$02B7	$1D03			BTFSS	STATUS, Z
$02B8	$2ABB			GOTO	L_VDelay_ms_0
$02B9	$30A3			MOVLW	163
$02BA	$0270			SUBWF	STACK_0, 0
$02BB	$	L_VDelay_ms_0:
$02BB	$1803			BTFSC	STATUS, C
$02BC	$2ABE			GOTO	delays_L_19
$02BD	$	delays_L_18:
;delays.pbas,70 :: 		exit
$02BD	$2B15			GOTO	delays_L_17
$02BE	$	delays_L_19:
;delays.pbas,71 :: 		end if
$02BE	$	delays_L_20:
;delays.pbas,72 :: 		NumberOfCyc = NumberOfCyc - 675
$02BE	$30A3			MOVLW	163
$02BF	$00F0			MOVWF	STACK_0
$02C0	$3002			MOVLW	2
$02C1	$00F1			MOVWF	STACK_0+1
$02C2	$01F2			CLRF	STACK_0+2
$02C3	$01F3			CLRF	STACK_0+3
$02C4	$0849			MOVF	_vdelay_ms_local_numberofcyc, 0
$02C5	$00F4			MOVWF	STACK_4
$02C6	$084A			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$02C7	$00F5			MOVWF	STACK_4+1
$02C8	$084B			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$02C9	$00F6			MOVWF	STACK_4+2
$02CA	$084C			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$02CB	$00F7			MOVWF	STACK_4+3
$02CC	$0870			MOVF	STACK_0, 0
$02CD	$02F4			SUBWF	STACK_4, 1
$02CE	$0871			MOVF	STACK_0+1, 0
$02CF	$1C03			BTFSS	STATUS, C
$02D0	$0F71			INCFSZ	STACK_0+1, 0
$02D1	$02F5			SUBWF	STACK_4+1, 1
$02D2	$0872			MOVF	STACK_0+2, 0
$02D3	$1C03			BTFSS	STATUS, C
$02D4	$0F72			INCFSZ	STACK_0+2, 0
$02D5	$02F6			SUBWF	STACK_4+2, 1
$02D6	$0873			MOVF	STACK_0+3, 0
$02D7	$1C03			BTFSS	STATUS, C
$02D8	$0F73			INCFSZ	STACK_0+3, 0
$02D9	$02F7			SUBWF	STACK_4+3, 1
$02DA	$0874			MOVF	STACK_4, 0
$02DB	$00C9			MOVWF	_vdelay_ms_local_numberofcyc
$02DC	$0875			MOVF	STACK_4+1, 0
$02DD	$00CA			MOVWF	_vdelay_ms_local_numberofcyc+1
$02DE	$0876			MOVF	STACK_4+2, 0
$02DF	$00CB			MOVWF	_vdelay_ms_local_numberofcyc+2
$02E0	$0877			MOVF	STACK_4+3, 0
$02E1	$00CC			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,73 :: 		NumberOfCyc = NumberOfCyc >> 5  ' Dec and While below take around 32 instructions
$02E2	$3005			MOVLW	5
$02E3	$00F0			MOVWF	STACK_0
$02E4	$0874			MOVF	STACK_4, 0
$02E5	$00C9			MOVWF	_vdelay_ms_local_numberofcyc
$02E6	$0875			MOVF	STACK_4+1, 0
$02E7	$00CA			MOVWF	_vdelay_ms_local_numberofcyc+1
$02E8	$0876			MOVF	STACK_4+2, 0
$02E9	$00CB			MOVWF	_vdelay_ms_local_numberofcyc+2
$02EA	$0877			MOVF	STACK_4+3, 0
$02EB	$00CC			MOVWF	_vdelay_ms_local_numberofcyc+3
$02EC	$0870			MOVF	STACK_0, 0
$02ED	$	L_VDelay_ms_1:
$02ED	$1903			BTFSC	STATUS, Z
$02EE	$2AF6			GOTO	L_VDelay_ms_2
$02EF	$0CCC			RRF	_vdelay_ms_local_numberofcyc+3, 1
$02F0	$0CCB			RRF	_vdelay_ms_local_numberofcyc+2, 1
$02F1	$0CCA			RRF	_vdelay_ms_local_numberofcyc+1, 1
$02F2	$0CC9			RRF	_vdelay_ms_local_numberofcyc, 1
$02F3	$13CC			BCF	_vdelay_ms_local_numberofcyc+3, 7
$02F4	$3FFF			ADDLW	255
$02F5	$2AED			GOTO	L_VDelay_ms_1
$02F6	$	L_VDelay_ms_2:
;delays.pbas,74 :: 		while ( Lo(NumberOfCyc) or Hi(NumberOfCyc) or Higher(NumberOfCyc) or Highest(NumberOfCyc) ) <> 0
$02F6	$	delays_L_22:
$02F6	$30FF			MOVLW	255
$02F7	$0549			ANDWF	_vdelay_ms_local_numberofcyc, 0
$02F8	$00F8			MOVWF	STACK_8
$02F9	$084A			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$02FA	$00F0			MOVWF	STACK_0
$02FB	$0870			MOVF	STACK_0, 0
$02FC	$04F8			IORWF	STACK_8, 1
$02FD	$084B			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$02FE	$00F0			MOVWF	STACK_0
$02FF	$084C			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0300	$00F1			MOVWF	STACK_0+1
$0301	$0870			MOVF	STACK_0, 0
$0302	$04F8			IORWF	STACK_8, 1
$0303	$084C			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0304	$00F0			MOVWF	STACK_0
$0305	$0870			MOVF	STACK_0, 0
$0306	$0478			IORWF	STACK_8, 0
$0307	$00F4			MOVWF	STACK_4
$0308	$0874			MOVF	STACK_4, 0
$0309	$3A00			XORLW	0
$030A	$1903			BTFSC	STATUS, Z
$030B	$2B15			GOTO	delays_L_23
;delays.pbas,75 :: 		Dec(NumberOfCyc)
$030C	$3001			MOVLW	1
$030D	$02C9			SUBWF	_vdelay_ms_local_numberofcyc, 1
$030E	$1C03			BTFSS	STATUS, C
$030F	$02CA			SUBWF	_vdelay_ms_local_numberofcyc+1, 1
$0310	$1C03			BTFSS	STATUS, C
$0311	$02CB			SUBWF	_vdelay_ms_local_numberofcyc+2, 1
$0312	$1C03			BTFSS	STATUS, C
$0313	$02CC			SUBWF	_vdelay_ms_local_numberofcyc+3, 1
$0314	$2AF6			GOTO	delays_L_22
$0315	$	delays_L_23:
;delays.pbas,76 :: 		wend
$0315	$	delays_L_17:
$0315	$0008			RETURN
$03C7	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$03C7	$1303			BCF	STATUS, RP1
$03C8	$1283			BCF	STATUS, RP0
$03C9	$01BC			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$03CA	$01BD			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$03CB	$01C0			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$03CC	$083B			MOVF	FARG_Usart_Read_Text+1, 0
$03CD	$0084			MOVWF	FSR
$03CE	$0800			MOVF	INDF, 0
$03CF	$00BF			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$03D0	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$03D0	$2515			CALL	_usart_data_ready
$03D1	$0870			MOVF	STACK_0, 0
$03D2	$3A00			XORLW	0
$03D3	$1903			BTFSC	STATUS, Z
$03D4	$2C00			GOTO	USART_b75_L_34
$03D5	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$03D5	$24F4			CALL	_usart_read
$03D6	$0870			MOVF	STACK_0, 0
$03D7	$00BE			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$03D8	$083C			MOVF	_usart_read_text_local_i, 0
$03D9	$073A			ADDWF	FARG_Usart_Read_Text, 0
$03DA	$00F1			MOVWF	STACK_1
$03DB	$0871			MOVF	STACK_1, 0
$03DC	$0084			MOVWF	FSR
$03DD	$0871			MOVF	STACK_1, 0
$03DE	$0084			MOVWF	FSR
$03DF	$0870			MOVF	STACK_0, 0
$03E0	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$03E1	$083E			MOVF	_usart_read_text_local_data, 0
$03E2	$063F			XORWF	_usart_read_text_local_data2, 0
$03E3	$1D03			BTFSS	STATUS, Z
$03E4	$2BEA			GOTO	USART_b75_L_37
$03E5	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$03E5	$083D			MOVF	_usart_read_text_local_j, 0
$03E6	$023C			SUBWF	_usart_read_text_local_i, 0
$03E7	$00C0			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$03E8	$0ABD			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$03E9	$2BEC			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$03EA	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$03EA	$01BD			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$03EB	$01C0			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$03EC	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$03EC	$083D			MOVF	_usart_read_text_local_j, 0
$03ED	$073B			ADDWF	FARG_Usart_Read_Text+1, 0
$03EE	$0084			MOVWF	FSR
$03EF	$0800			MOVF	INDF, 0
$03F0	$00F1			MOVWF	STACK_1
$03F1	$0871			MOVF	STACK_1, 0
$03F2	$00BF			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$03F3	$0871			MOVF	STACK_1, 0
$03F4	$3A00			XORLW	0
$03F5	$1D03			BTFSS	STATUS, Z
$03F6	$2BF8			GOTO	USART_b75_L_40
$03F7	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$03F7	$2C01			GOTO	USART_b75_L_30
$03F8	$	USART_b75_L_40:
$03F8	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$03F8	$0ABC			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$03F9	$083C			MOVF	_usart_read_text_local_i, 0
$03FA	$3C14			SUBLW	20
$03FB	$1803			BTFSC	STATUS, C
$03FC	$2C00			GOTO	USART_b75_L_43
$03FD	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$03FD	$3013			MOVLW	19
$03FE	$00C0			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$03FF	$2C01			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0400	$	USART_b75_L_43:
$0400	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0400	$	USART_b75_L_34:
$0400	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0400	$2BD0			GOTO	USART_b75_L_29
$0401	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0401	$0840			MOVF	_usart_read_text_local_lasti, 0
$0402	$073A			ADDWF	FARG_Usart_Read_Text, 0
$0403	$00F0			MOVWF	STACK_0
$0404	$0870			MOVF	STACK_0, 0
$0405	$0084			MOVWF	FSR
$0406	$0870			MOVF	STACK_0, 0
$0407	$0084			MOVWF	FSR
$0408	$0180			CLRF	INDF, 1
$0409	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$0409	$0008			RETURN
$0132	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$0132	$1303			BCF	STATUS, RP1
$0133	$1283			BCF	STATUS, RP0
$0134	$01BB			CLRF	_strtoint_local_result
$0135	$01BC			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0136	$3010			MOVLW	16
$0137	$00BF			MOVWF	_strtoint_local_ep
$0138	$3027			MOVLW	39
$0139	$00C0			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$013A	$01BD			CLRF	_strtoint_local_i
$013B	$01BE			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$013C	$01C3			CLRF	_strtoint_local_tmp
$013D	$01C4			CLRF	_strtoint_local_tmp+1
$013E	$01C5			CLRF	_strtoint_local_tmp+2
$013F	$01C6			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$0140	$01C1			CLRF	_strtoint_local_negative
$0141	$01C2			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$0142	$	conv_L_172:
$0142	$083D			MOVF	_strtoint_local_i, 0
$0143	$073A			ADDWF	FARG_StrToInt, 0
$0144	$0084			MOVWF	FSR
$0145	$0800			MOVF	INDF, 0
$0146	$00F4			MOVWF	STACK_4
$0147	$0874			MOVF	STACK_4, 0
$0148	$3A00			XORLW	0
$0149	$1903			BTFSC	STATUS, Z
$014A	$29AE			GOTO	conv_L_173
;conv.ppas,355 :: 		
$014B	$083D			MOVF	_strtoint_local_i, 0
$014C	$073A			ADDWF	FARG_StrToInt, 0
$014D	$0084			MOVWF	FSR
$014E	$0800			MOVF	INDF, 0
$014F	$00F4			MOVWF	STACK_4
$0150	$0874			MOVF	STACK_4, 0
$0151	$3A2D			XORLW	45
$0152	$1D03			BTFSS	STATUS, Z
$0153	$295B			GOTO	conv_L_177
$0154	$	conv_L_176:
;conv.ppas,357 :: 		
$0154	$30FF			MOVLW	255
$0155	$00C1			MOVWF	_strtoint_local_negative
$0156	$01C2			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0157	$0ABD			INCF	_strtoint_local_i, 1
$0158	$1903			BTFSC	STATUS, Z
$0159	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$015A	$2942			GOTO	conv_L_172
;conv.ppas,360 :: 		
$015B	$	conv_L_177:
$015B	$	conv_L_178:
;conv.ppas,361 :: 		
$015B	$083D			MOVF	_strtoint_local_i, 0
$015C	$073A			ADDWF	FARG_StrToInt, 0
$015D	$0084			MOVWF	FSR
$015E	$0800			MOVF	INDF, 0
$015F	$00F4			MOVWF	STACK_4
$0160	$0874			MOVF	STACK_4, 0
$0161	$3A20			XORLW	32
$0162	$1903			BTFSC	STATUS, Z
$0163	$299E			GOTO	conv_L_180
$0164	$	conv_L_179:
;conv.ppas,362 :: 		
$0164	$083D			MOVF	_strtoint_local_i, 0
$0165	$073A			ADDWF	FARG_StrToInt, 0
$0166	$0084			MOVWF	FSR
$0167	$0800			MOVF	INDF, 0
$0168	$00F0			MOVWF	STACK_0
$0169	$3030			MOVLW	48
$016A	$00F8			MOVWF	STACK_8
$016B	$01F9			CLRF	STACK_8+1
$016C	$01FA			CLRF	STACK_8+2
$016D	$01FB			CLRF	STACK_8+3
$016E	$0870			MOVF	STACK_0, 0
$016F	$00F4			MOVWF	STACK_4
$0170	$01F5			CLRF	STACK_4+1
$0171	$01F6			CLRF	STACK_4+2
$0172	$01F7			CLRF	STACK_4+3
$0173	$0874			MOVF	STACK_4, 0
$0174	$00F0			MOVWF	STACK_0
$0175	$0875			MOVF	STACK_4+1, 0
$0176	$00F1			MOVWF	STACK_0+1
$0177	$0876			MOVF	STACK_4+2, 0
$0178	$00F2			MOVWF	STACK_0+2
$0179	$0877			MOVF	STACK_4+3, 0
$017A	$00F3			MOVWF	STACK_0+3
$017B	$0878			MOVF	STACK_8, 0
$017C	$02F0			SUBWF	STACK_0, 1
$017D	$0879			MOVF	STACK_8+1, 0
$017E	$1C03			BTFSS	STATUS, C
$017F	$0F79			INCFSZ	STACK_8+1, 0
$0180	$02F1			SUBWF	STACK_0+1, 1
$0181	$087A			MOVF	STACK_8+2, 0
$0182	$1C03			BTFSS	STATUS, C
$0183	$0F7A			INCFSZ	STACK_8+2, 0
$0184	$02F2			SUBWF	STACK_0+2, 1
$0185	$087B			MOVF	STACK_8+3, 0
$0186	$1C03			BTFSS	STATUS, C
$0187	$0F7B			INCFSZ	STACK_8+3, 0
$0188	$02F3			SUBWF	STACK_0+3, 1
$0189	$083F			MOVF	_strtoint_local_ep, 0
$018A	$00F4			MOVWF	STACK_4
$018B	$0840			MOVF	_strtoint_local_ep+1, 0
$018C	$00F5			MOVWF	STACK_4+1
$018D	$01F6			CLRF	STACK_4+2
$018E	$01F7			CLRF	STACK_4+3
$018F	$2450			CALL	_mul_32x32_s
$0190	$0870			MOVF	STACK_0, 0
$0191	$07C3			ADDWF	_strtoint_local_tmp, 1
$0192	$0871			MOVF	STACK_0+1, 0
$0193	$1803			BTFSC	STATUS, C
$0194	$0F71			INCFSZ	STACK_0+1, 0
$0195	$07C4			ADDWF	_strtoint_local_tmp+1, 1
$0196	$0872			MOVF	STACK_0+2, 0
$0197	$1803			BTFSC	STATUS, C
$0198	$0F72			INCFSZ	STACK_0+2, 0
$0199	$07C5			ADDWF	_strtoint_local_tmp+2, 1
$019A	$0873			MOVF	STACK_0+3, 0
$019B	$1803			BTFSC	STATUS, C
$019C	$0F73			INCFSZ	STACK_0+3, 0
$019D	$07C6			ADDWF	_strtoint_local_tmp+3, 1
$019E	$	conv_L_180:
$019E	$	conv_L_181:
;conv.ppas,363 :: 		
$019E	$300A			MOVLW	10
$019F	$00F4			MOVWF	STACK_4
$01A0	$01F5			CLRF	STACK_4+1
$01A1	$083F			MOVF	_strtoint_local_ep, 0
$01A2	$00F0			MOVWF	STACK_0
$01A3	$0840			MOVF	_strtoint_local_ep+1, 0
$01A4	$00F1			MOVWF	STACK_0+1
$01A5	$24C2			CALL	_div_16x16_u
$01A6	$0870			MOVF	STACK_0, 0
$01A7	$00BF			MOVWF	_strtoint_local_ep
$01A8	$0871			MOVF	STACK_0+1, 0
$01A9	$00C0			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$01AA	$0ABD			INCF	_strtoint_local_i, 1
$01AB	$1903			BTFSC	STATUS, Z
$01AC	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$01AD	$2942			GOTO	conv_L_172
$01AE	$	conv_L_173:
;conv.ppas,370 :: 		
$01AE	$0841			MOVF	_strtoint_local_negative, 0
$01AF	$0442			IORWF	_strtoint_local_negative+1, 0
$01B0	$1903			BTFSC	STATUS, Z
$01B1	$29B6			GOTO	conv_L_183
$01B2	$	conv_L_182:
$01B2	$3006			MOVLW	6
$01B3	$00BF			MOVWF	_strtoint_local_ep
$01B4	$01C0			CLRF	_strtoint_local_ep+1
$01B5	$29B9			GOTO	conv_L_184
;conv.ppas,371 :: 		
$01B6	$	conv_L_183:
$01B6	$3005			MOVLW	5
$01B7	$00BF			MOVWF	_strtoint_local_ep
$01B8	$01C0			CLRF	_strtoint_local_ep+1
$01B9	$	conv_L_184:
;conv.ppas,373 :: 		
$01B9	$	conv_L_186:
$01B9	$083E			MOVF	_strtoint_local_i+1, 0
$01BA	$0640			XORWF	_strtoint_local_ep+1, 0
$01BB	$1D03			BTFSS	STATUS, Z
$01BC	$29BF			GOTO	L_StrToInt_20
$01BD	$083F			MOVF	_strtoint_local_ep, 0
$01BE	$063D			XORWF	_strtoint_local_i, 0
$01BF	$	L_StrToInt_20:
$01BF	$1903			BTFSC	STATUS, Z
$01C0	$29DB			GOTO	conv_L_187
;conv.ppas,375 :: 		
$01C1	$300A			MOVLW	10
$01C2	$00F4			MOVWF	STACK_4
$01C3	$01F5			CLRF	STACK_4+1
$01C4	$01F6			CLRF	STACK_4+2
$01C5	$01F7			CLRF	STACK_4+3
$01C6	$0843			MOVF	_strtoint_local_tmp, 0
$01C7	$00F0			MOVWF	STACK_0
$01C8	$0844			MOVF	_strtoint_local_tmp+1, 0
$01C9	$00F1			MOVWF	STACK_0+1
$01CA	$0845			MOVF	_strtoint_local_tmp+2, 0
$01CB	$00F2			MOVWF	STACK_0+2
$01CC	$0846			MOVF	_strtoint_local_tmp+3, 0
$01CD	$00F3			MOVWF	STACK_0+3
$01CE	$21F4			CALL	_div_32x32_s
$01CF	$0870			MOVF	STACK_0, 0
$01D0	$00C3			MOVWF	_strtoint_local_tmp
$01D1	$0871			MOVF	STACK_0+1, 0
$01D2	$00C4			MOVWF	_strtoint_local_tmp+1
$01D3	$0872			MOVF	STACK_0+2, 0
$01D4	$00C5			MOVWF	_strtoint_local_tmp+2
$01D5	$0873			MOVF	STACK_0+3, 0
$01D6	$00C6			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$01D7	$0ABD			INCF	_strtoint_local_i, 1
$01D8	$1903			BTFSC	STATUS, Z
$01D9	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$01DA	$29B9			GOTO	conv_L_186
$01DB	$	conv_L_187:
;conv.ppas,380 :: 		
$01DB	$0843			MOVF	_strtoint_local_tmp, 0
$01DC	$00BB			MOVWF	_strtoint_local_result
$01DD	$0844			MOVF	_strtoint_local_tmp+1, 0
$01DE	$00BC			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$01DF	$3000			MOVLW	0
$01E0	$0642			XORWF	_strtoint_local_negative+1, 0
$01E1	$1D03			BTFSS	STATUS, Z
$01E2	$29E5			GOTO	L_StrToInt_21
$01E3	$30FF			MOVLW	255
$01E4	$0641			XORWF	_strtoint_local_negative, 0
$01E5	$	L_StrToInt_21:
$01E5	$1D03			BTFSS	STATUS, Z
$01E6	$29EF			GOTO	conv_L_191
$01E7	$	conv_L_190:
;conv.ppas,383 :: 		
$01E7	$083B			MOVF	_strtoint_local_result, 0
$01E8	$3C00			SUBLW	0
$01E9	$00BB			MOVWF	_strtoint_local_result
$01EA	$083C			MOVF	_strtoint_local_result+1, 0
$01EB	$1C03			BTFSS	STATUS, C
$01EC	$3F01			ADDLW	1
$01ED	$01BC			CLRF	_strtoint_local_result+1
$01EE	$02BC			SUBWF	_strtoint_local_result+1, 1
$01EF	$	conv_L_191:
$01EF	$	conv_L_192:
$01EF	$	conv_L_170:
;conv.ppas,384 :: 		
$01EF	$083B			MOVF	_strtoint_local_result, 0
$01F0	$00F0			MOVWF	STACK_0
$01F1	$083C			MOVF	_strtoint_local_result+1, 0
$01F2	$00F1			MOVWF	STACK_0+1
$01F3	$0008			RETURN
$040A	$	_strcmp:
;StringsLib.ppas,172 :: 		
;StringsLib.ppas,173 :: 		
$040A	$1303			BCF	STATUS, RP1
$040B	$1283			BCF	STATUS, RP0
$040C	$01BE			CLRF	_strcmp_local_i, 1
;StringsLib.ppas,174 :: 		
$040D	$083A			MOVF	FARG_strcmp, 0
$040E	$0084			MOVWF	FSR
$040F	$0800			MOVF	INDF, 0
$0410	$00BC			MOVWF	_strcmp_local_result
$0411	$01BD			CLRF	_strcmp_local_result+1
;StringsLib.ppas,175 :: 		
$0412	$083B			MOVF	FARG_strcmp+1, 0
$0413	$0084			MOVWF	FSR
$0414	$0800			MOVF	INDF, 0
$0415	$00F0			MOVWF	STACK_0
;StringsLib.ppas,176 :: 		
$0416	$3000			MOVLW	0
$0417	$00BD			MOVWF	_strcmp_local_result+1
$0418	$0870			MOVF	STACK_0, 0
$0419	$02BC			SUBWF	_strcmp_local_result, 1
$041A	$1C03			BTFSS	STATUS, C
$041B	$03BD			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,177 :: 		
$041C	$	StringsLib_L_77:
$041C	$3000			MOVLW	0
$041D	$063D			XORWF	_strcmp_local_result+1, 0
$041E	$1D03			BTFSS	STATUS, Z
$041F	$2C22			GOTO	L_strcmp_8
$0420	$3000			MOVLW	0
$0421	$063C			XORWF	_strcmp_local_result, 0
$0422	$	L_strcmp_8:
$0422	$30FF			MOVLW	255
$0423	$1D03			BTFSS	STATUS, Z
$0424	$3000			MOVLW	0
$0425	$00F3			MOVWF	STACK_3
$0426	$083E			MOVF	_strcmp_local_i, 0
$0427	$073A			ADDWF	FARG_strcmp, 0
$0428	$0084			MOVWF	FSR
$0429	$0800			MOVF	INDF, 0
$042A	$00F2			MOVWF	STACK_2
$042B	$0872			MOVF	STACK_2, 0
$042C	$3A00			XORLW	0
$042D	$30FF			MOVLW	255
$042E	$1903			BTFSC	STATUS, Z
$042F	$3000			MOVLW	0
$0430	$00F0			MOVWF	STACK_0
$0431	$0873			MOVF	STACK_3, 0
$0432	$05F0			ANDWF	STACK_0, 1
$0433	$1903			BTFSC	STATUS, Z
$0434	$2C4B			GOTO	StringsLib_L_78
;StringsLib.ppas,179 :: 		
$0435	$0A3E			INCF	_strcmp_local_i, 0
$0436	$00F0			MOVWF	STACK_0
$0437	$0870			MOVF	STACK_0, 0
$0438	$00BE			MOVWF	_strcmp_local_i
;StringsLib.ppas,180 :: 		
$0439	$0870			MOVF	STACK_0, 0
$043A	$073A			ADDWF	FARG_strcmp, 0
$043B	$0084			MOVWF	FSR
$043C	$0800			MOVF	INDF, 0
$043D	$00BC			MOVWF	_strcmp_local_result
$043E	$01BD			CLRF	_strcmp_local_result+1
;StringsLib.ppas,181 :: 		
$043F	$0870			MOVF	STACK_0, 0
$0440	$073B			ADDWF	FARG_strcmp+1, 0
$0441	$0084			MOVWF	FSR
$0442	$0800			MOVF	INDF, 0
$0443	$00F0			MOVWF	STACK_0
;StringsLib.ppas,182 :: 		
$0444	$3000			MOVLW	0
$0445	$00BD			MOVWF	_strcmp_local_result+1
$0446	$0870			MOVF	STACK_0, 0
$0447	$02BC			SUBWF	_strcmp_local_result, 1
$0448	$1C03			BTFSS	STATUS, C
$0449	$03BD			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,183 :: 		
$044A	$2C1C			GOTO	StringsLib_L_77
$044B	$	StringsLib_L_78:
$044B	$	StringsLib_L_75:
;StringsLib.ppas,184 :: 		
$044B	$083C			MOVF	_strcmp_local_result, 0
$044C	$00F0			MOVWF	STACK_0
$044D	$083D			MOVF	_strcmp_local_result+1, 0
$044E	$00F1			MOVWF	STACK_0+1
$044F	$0008			RETURN
$0316	$	_giramotor:
;DriverDeControle.pbas,11 :: 		sub procedure giraMotor(dim ciclo as integer)
;DriverDeControle.pbas,13 :: 		for x = 1 to ciclo
$0316	$3001			MOVLW	1
$0317	$1303			BCF	STATUS, RP1
$0318	$1283			BCF	STATUS, RP0
$0319	$00A1			MOVWF	_x
$031A	$01A2			CLRF	_x+1
$031B	$	DriverDeControle_L_1:
$031B	$3080			MOVLW	128
$031C	$063B			XORWF	FARG_giraMotor+1, 0
$031D	$00F0			MOVWF	STACK_0
$031E	$3080			MOVLW	128
$031F	$0622			XORWF	_x+1, 0
$0320	$0270			SUBWF	STACK_0, 0
$0321	$1D03			BTFSS	STATUS, Z
$0322	$2B25			GOTO	L_giraMotor_0
$0323	$0821			MOVF	_x, 0
$0324	$023A			SUBWF	FARG_giraMotor, 0
$0325	$	L_giraMotor_0:
$0325	$1C03			BTFSS	STATUS, C
$0326	$2B70			GOTO	DriverDeControle_L_4
;DriverDeControle.pbas,14 :: 		if invert = true then
$0327	$0823			MOVF	_invert, 0
$0328	$3AFF			XORLW	255
$0329	$1D03			BTFSS	STATUS, Z
$032A	$2B48			GOTO	DriverDeControle_L_6
$032B	$	DriverDeControle_L_5:
;DriverDeControle.pbas,15 :: 		PORTC=1 vdelay_ms(tmpOn)
$032B	$3001			MOVLW	1
$032C	$0087			MOVWF	PORTC
$032D	$0824			MOVF	_tmpon, 0
$032E	$00C7			MOVWF	FARG_VDelay_ms
$032F	$0825			MOVF	_tmpon+1, 0
$0330	$00C8			MOVWF	FARG_VDelay_ms+1
$0331	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,16 :: 		PORTC=2 vdelay_ms(tmpOn)
$0332	$3002			MOVLW	2
$0333	$0087			MOVWF	PORTC
$0334	$0824			MOVF	_tmpon, 0
$0335	$00C7			MOVWF	FARG_VDelay_ms
$0336	$0825			MOVF	_tmpon+1, 0
$0337	$00C8			MOVWF	FARG_VDelay_ms+1
$0338	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,17 :: 		PORTC=4 vdelay_ms(tmpOn)
$0339	$3004			MOVLW	4
$033A	$0087			MOVWF	PORTC
$033B	$0824			MOVF	_tmpon, 0
$033C	$00C7			MOVWF	FARG_VDelay_ms
$033D	$0825			MOVF	_tmpon+1, 0
$033E	$00C8			MOVWF	FARG_VDelay_ms+1
$033F	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,18 :: 		PORTC=8 vdelay_ms(tmpOn)
$0340	$3008			MOVLW	8
$0341	$0087			MOVWF	PORTC
$0342	$0824			MOVF	_tmpon, 0
$0343	$00C7			MOVWF	FARG_VDelay_ms
$0344	$0825			MOVF	_tmpon+1, 0
$0345	$00C8			MOVWF	FARG_VDelay_ms+1
$0346	$228E			CALL	_vdelay_ms
$0347	$2B64			GOTO	DriverDeControle_L_7
;DriverDeControle.pbas,19 :: 		else
$0348	$	DriverDeControle_L_6:
;DriverDeControle.pbas,20 :: 		PORTC=8 vdelay_ms(tmpOn)
$0348	$3008			MOVLW	8
$0349	$0087			MOVWF	PORTC
$034A	$0824			MOVF	_tmpon, 0
$034B	$00C7			MOVWF	FARG_VDelay_ms
$034C	$0825			MOVF	_tmpon+1, 0
$034D	$00C8			MOVWF	FARG_VDelay_ms+1
$034E	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,21 :: 		PORTC=4 vdelay_ms(tmpOn)
$034F	$3004			MOVLW	4
$0350	$0087			MOVWF	PORTC
$0351	$0824			MOVF	_tmpon, 0
$0352	$00C7			MOVWF	FARG_VDelay_ms
$0353	$0825			MOVF	_tmpon+1, 0
$0354	$00C8			MOVWF	FARG_VDelay_ms+1
$0355	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,22 :: 		PORTC=2 vdelay_ms(tmpOn)
$0356	$3002			MOVLW	2
$0357	$0087			MOVWF	PORTC
$0358	$0824			MOVF	_tmpon, 0
$0359	$00C7			MOVWF	FARG_VDelay_ms
$035A	$0825			MOVF	_tmpon+1, 0
$035B	$00C8			MOVWF	FARG_VDelay_ms+1
$035C	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,23 :: 		PORTC=1 vdelay_ms(tmpOn)
$035D	$3001			MOVLW	1
$035E	$0087			MOVWF	PORTC
$035F	$0824			MOVF	_tmpon, 0
$0360	$00C7			MOVWF	FARG_VDelay_ms
$0361	$0825			MOVF	_tmpon+1, 0
$0362	$00C8			MOVWF	FARG_VDelay_ms+1
$0363	$228E			CALL	_vdelay_ms
;DriverDeControle.pbas,24 :: 		end if
$0364	$	DriverDeControle_L_7:
;DriverDeControle.pbas,25 :: 		next x
$0364	$0822			MOVF	_x+1, 0
$0365	$063B			XORWF	FARG_giraMotor+1, 0
$0366	$1D03			BTFSS	STATUS, Z
$0367	$2B6A			GOTO	L_giraMotor_1
$0368	$083A			MOVF	FARG_giraMotor, 0
$0369	$0621			XORWF	_x, 0
$036A	$	L_giraMotor_1:
$036A	$1903			BTFSC	STATUS, Z
$036B	$2B70			GOTO	DriverDeControle_L_4
$036C	$	DriverDeControle_L_2:
$036C	$0AA1			INCF	_x, 1
$036D	$1903			BTFSC	STATUS, Z
$036E	$0AA2			INCF	_x+1, 1
$036F	$2B1B			GOTO	DriverDeControle_L_1
$0370	$	DriverDeControle_L_4:
;DriverDeControle.pbas,27 :: 		PORTC=0
$0370	$0187			CLRF	PORTC, 1
$0371	$	DriverDeControle_L_0:
$0371	$0008			RETURN
$04DF	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$04DF	$	USART_b75_L_1:
$04DF	$1303			BCF	STATUS, RP1
$04E0	$1683			BSF	STATUS, RP0
$04E1	$1698			BSF	TXSTA, 5
$04E2	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$04E2	$3090			MOVLW	144
$04E3	$1283			BCF	STATUS, RP0
$04E4	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$04E5	$	USART_b75_L_3:
$04E5	$1683			BSF	STATUS, RP0
$04E6	$1686			BSF	TRISB, 5
$04E7	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$04E7	$	USART_b75_L_5:
$04E7	$1786			BSF	TRISB, 7
$04E8	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$04E8	$	USART_b75_L_8:
$04E8	$1283			BCF	STATUS, RP0
$04E9	$080C			MOVF	PIR1, 0
$04EA	$00F1			MOVWF	STACK_1
$04EB	$3000			MOVLW	0
$04EC	$1AF1			BTFSC	STACK_1, 5
$04ED	$3001			MOVLW	1
$04EE	$00F1			MOVWF	STACK_1
$04EF	$0871			MOVF	STACK_1, 0
$04F0	$3A01			XORLW	1
$04F1	$1903			BTFSC	STATUS, Z
$04F2	$2CE8			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$04F3	$	USART_b75_L_9:
$04F3	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$04F3	$0008			RETURN
$0372	$	_main:
;DriverDeControle.pbas,31 :: 		main:
$0372	$	_main_main:
;DriverDeControle.pbas,32 :: 		TRISA=%11111110
$0372	$30FE			MOVLW	254
$0373	$1303			BCF	STATUS, RP1
$0374	$1683			BSF	STATUS, RP0
$0375	$0085			MOVWF	TRISA
;DriverDeControle.pbas,33 :: 		TRISB=%01111111
$0376	$307F			MOVLW	127
$0377	$0086			MOVWF	TRISB
;DriverDeControle.pbas,34 :: 		TRISC=%00000000
$0378	$0187			CLRF	TRISC, 1
;DriverDeControle.pbas,35 :: 		INTCON=%00000000
$0379	$018B			CLRF	INTCON, 1
;DriverDeControle.pbas,36 :: 		ANSEL=%00000000
$037A	$1703			BSF	STATUS, RP1
$037B	$1283			BCF	STATUS, RP0
$037C	$019E			CLRF	ANSEL, 1
;DriverDeControle.pbas,37 :: 		ANSELH=%00000000
$037D	$019F			CLRF	ANSELH, 1
;DriverDeControle.pbas,38 :: 		PORTC=0
$037E	$1303			BCF	STATUS, RP1
$037F	$0187			CLRF	PORTC, 1
;DriverDeControle.pbas,40 :: 		Usart_Init(9600)
$0380	$3019			MOVLW	25
$0381	$1683			BSF	STATUS, RP0
$0382	$0099			MOVWF	SPBRG
$0383	$1518			BSF	TXSTA, BRGH
$0384	$24DF			CALL	_usart_init
;DriverDeControle.pbas,42 :: 		tmpOn=50
$0385	$3032			MOVLW	50
$0386	$00A4			MOVWF	_tmpon
$0387	$01A5			CLRF	_tmpon+1
;DriverDeControle.pbas,43 :: 		tmpOff=0
$0388	$01A6			CLRF	_tmpoff
$0389	$01A7			CLRF	_tmpoff+1
;DriverDeControle.pbas,44 :: 		invert=false
$038A	$01A3			CLRF	_invert, 1
;DriverDeControle.pbas,46 :: 		executa:
$038B	$	_main_executa:
;DriverDeControle.pbas,47 :: 		if Usart_Data_Ready() > 0 then
$038B	$2515			CALL	_usart_data_ready
$038C	$0870			MOVF	STACK_0, 0
$038D	$3C00			SUBLW	0
$038E	$1803			BTFSC	STATUS, C
$038F	$2BC2			GOTO	DriverDeControle_L_10
$0390	$	DriverDeControle_L_9:
;DriverDeControle.pbas,49 :: 		Usart_Read_Text(valorStr,"-")
$0390	$3028			MOVLW	_valorstr
$0391	$00BA			MOVWF	FARG_Usart_Read_Text
$0392	$302D			MOVLW	45
$0393	$00B8			MOVWF	?main_Local_Text+0
$0394	$01B9			CLRF	?main_Local_Text+1
$0395	$3038			MOVLW	?main_Local_Text
$0396	$00BB			MOVWF	FARG_Usart_Read_Text+1
$0397	$23C7			CALL	_usart_read_text
;DriverDeControle.pbas,50 :: 		Usart_Read_Text(invertStr,"/")
$0398	$302F			MOVLW	_invertstr
$0399	$00BA			MOVWF	FARG_Usart_Read_Text
$039A	$302F			MOVLW	47
$039B	$00B8			MOVWF	?main_Local_Text+0
$039C	$01B9			CLRF	?main_Local_Text+1
$039D	$3038			MOVLW	?main_Local_Text
$039E	$00BB			MOVWF	FARG_Usart_Read_Text+1
$039F	$23C7			CALL	_usart_read_text
;DriverDeControle.pbas,51 :: 		valor = StrToInt(valorStr)
$03A0	$3028			MOVLW	_valorstr
$03A1	$00BA			MOVWF	FARG_StrToInt
$03A2	$2132			CALL	_strtoint
$03A3	$0870			MOVF	STACK_0, 0
$03A4	$00B6			MOVWF	_valor
$03A5	$0871			MOVF	STACK_0+1, 0
$03A6	$00B7			MOVWF	_valor+1
;DriverDeControle.pbas,53 :: 		if strcmp(invertStr, "N") = 0 then
$03A7	$302F			MOVLW	_invertstr
$03A8	$00BA			MOVWF	FARG_strcmp
$03A9	$304E			MOVLW	78
$03AA	$00B8			MOVWF	?main_Local_Text+0
$03AB	$01B9			CLRF	?main_Local_Text+1
$03AC	$3038			MOVLW	?main_Local_Text
$03AD	$00BB			MOVWF	FARG_strcmp+1
$03AE	$240A			CALL	_strcmp
$03AF	$3000			MOVLW	0
$03B0	$0671			XORWF	STACK_0+1, 0
$03B1	$1D03			BTFSS	STATUS, Z
$03B2	$2BB5			GOTO	L_main_2
$03B3	$3000			MOVLW	0
$03B4	$0670			XORWF	STACK_0, 0
$03B5	$	L_main_2:
$03B5	$1D03			BTFSS	STATUS, Z
$03B6	$2BBB			GOTO	DriverDeControle_L_13
$03B7	$	DriverDeControle_L_12:
;DriverDeControle.pbas,54 :: 		invert = true
$03B7	$30FF			MOVLW	255
$03B8	$00A3			MOVWF	_invert
;DriverDeControle.pbas,55 :: 		porta.0 = 1
$03B9	$	DriverDeControle_L_15:
$03B9	$1405			BSF	PORTA, 0
$03BA	$	DriverDeControle_L_16:
$03BA	$2BBD			GOTO	DriverDeControle_L_14
;DriverDeControle.pbas,56 :: 		else
$03BB	$	DriverDeControle_L_13:
;DriverDeControle.pbas,57 :: 		invert = false
$03BB	$01A3			CLRF	_invert, 1
;DriverDeControle.pbas,58 :: 		porta.0 = 0
$03BC	$1005			BCF	PORTA, 0
$03BD	$	DriverDeControle_L_18:
;DriverDeControle.pbas,59 :: 		end if
$03BD	$	DriverDeControle_L_14:
;DriverDeControle.pbas,61 :: 		giraMotor(valor)
$03BD	$0836			MOVF	_valor, 0
$03BE	$00BA			MOVWF	FARG_giraMotor
$03BF	$0837			MOVF	_valor+1, 0
$03C0	$00BB			MOVWF	FARG_giraMotor+1
$03C1	$2316			CALL	_giramotor
$03C2	$	DriverDeControle_L_10:
;DriverDeControle.pbas,63 :: 		end if
$03C2	$	DriverDeControle_L_11:
;DriverDeControle.pbas,65 :: 		valorStr=""
$03C2	$01A8			CLRF	_valorstr+0
;DriverDeControle.pbas,66 :: 		invert=""
$03C3	$3030			MOVLW	48
$03C4	$00A3			MOVWF	_invert
;DriverDeControle.pbas,68 :: 		goto executa
$03C5	$2B8B			GOTO	_main_executa
$03C6	$2BC6			GOTO	$
