;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 09/09/2020 15:24:46
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2A8E			GOTO	_main
$054D	$	_mul_32x32_u:
$054D	$1303			BCF	STATUS, RP1
$054E	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$054F	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0550	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0551	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0552	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0553	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0554	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$0555	$	_NEXT:
;math.ppas,1589 :: 		
$0555	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$0556	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0557	$2D83			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0558	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0559	$	_LOOP:
;math.ppas,1603 :: 		
$0559	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$055A	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$055B	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$055C	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$055D	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$055E	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$055F	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0560	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0561	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0562	$2D55			GOTO	_NEXT
;math.ppas,1617 :: 		
$0563	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$0564	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$0565	$2D75			GOTO	_EXIT1
;math.ppas,1626 :: 		
$0566	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$0567	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0568	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0569	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$056A	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$056B	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$056C	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$056D	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$056E	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$056F	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0570	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0571	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0572	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0573	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0574	$2D59			GOTO	_LOOP
;math.ppas,1647 :: 		
$0575	$	_EXIT1:
;math.ppas,1648 :: 		
$0575	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$0576	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0577	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0578	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0579	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$057A	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$057B	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$057C	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$057D	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$057E	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$057F	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0580	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0581	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0582	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0583	$	_EXIT2:
;math.ppas,1665 :: 		
$0583	$	math_L_13:
;math.ppas,1666 :: 		
$0583	$0008			RETURN
$0004	$	_sdiv3232l:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0006	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0007	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0008	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0009	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$000A	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$000B	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$000C	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$000D	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$000E	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$000F	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0010	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0011	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0012	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0013	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0014	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0015	$3007			MOVLW	7
;math.ppas,559 :: 		
$0016	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0017	$	LOOPS3232A:
;math.ppas,561 :: 		
$0017	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0018	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0019	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$001A	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$001B	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$001C	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$001D	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$001E	$282D			GOTO	SADD22LA
;math.ppas,570 :: 		
$001F	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0020	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0021	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0022	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0023	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0024	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0025	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0026	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0027	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0028	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0029	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$002A	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$002B	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$002C	$283A			GOTO	SOK22LA
;math.ppas,585 :: 		
$002D	$	SADD22LA:
;math.ppas,586 :: 		
$002D	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$002E	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$002F	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0030	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0031	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0032	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0033	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0034	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0035	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0036	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0037	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0038	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0039	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$003A	$	SOK22LA:
;math.ppas,602 :: 		
$003A	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$003B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$003C	$2817			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$003D	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$003E	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$003F	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0040	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0041	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0042	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0043	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0044	$2853			GOTO	SADD22L8
;math.ppas,615 :: 		
$0045	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0046	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0047	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0048	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0049	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$004A	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$004B	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$004C	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$004D	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$004E	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$004F	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0050	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0051	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0052	$2860			GOTO	SOK22L8
;math.ppas,630 :: 		
$0053	$	SADD22L8:
;math.ppas,631 :: 		
$0053	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0054	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0055	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0056	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0057	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0058	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0059	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$005A	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$005B	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$005C	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$005D	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$005E	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$005F	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0060	$	SOK22L8:
;math.ppas,647 :: 		
$0060	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0061	$3007			MOVLW	7
;math.ppas,650 :: 		
$0062	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0063	$	LOOPS3232B:
;math.ppas,652 :: 		
$0063	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0064	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0065	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0066	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0067	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0068	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0069	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$006A	$2879			GOTO	SADD22LB
;math.ppas,661 :: 		
$006B	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$006C	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$006D	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$006E	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$006F	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0070	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0071	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0072	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0073	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0074	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0075	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0076	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0077	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0078	$2886			GOTO	SOK22LB
;math.ppas,676 :: 		
$0079	$	SADD22LB:
;math.ppas,677 :: 		
$0079	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$007A	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$007B	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$007C	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$007D	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$007E	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$007F	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0080	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0081	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0082	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0083	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0084	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0085	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0086	$	SOK22LB:
;math.ppas,693 :: 		
$0086	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0087	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0088	$2863			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$0089	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$008A	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$008B	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$008C	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$008D	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$008E	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$008F	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0090	$289F			GOTO	SADD22L16
;math.ppas,706 :: 		
$0091	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0092	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0093	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0094	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0095	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0096	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0097	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0098	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0099	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$009A	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$009B	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$009C	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$009D	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$009E	$28AC			GOTO	SOK22L16
;math.ppas,721 :: 		
$009F	$	SADD22L16:
;math.ppas,722 :: 		
$009F	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$00A0	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$00A1	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$00A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$00A3	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$00A4	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$00A5	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$00A6	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$00A7	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$00A8	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$00A9	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$00AA	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$00AB	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$00AC	$	SOK22L16:
;math.ppas,738 :: 		
$00AC	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$00AD	$3007			MOVLW	7
;math.ppas,741 :: 		
$00AE	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$00AF	$	LOOPS3232C:
;math.ppas,743 :: 		
$00AF	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$00B0	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$00B1	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$00B2	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$00B3	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$00B4	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$00B5	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$00B6	$28C5			GOTO	SADD22LC
;math.ppas,752 :: 		
$00B7	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$00B8	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$00B9	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$00BA	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$00BB	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$00BC	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$00BD	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$00BE	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$00BF	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$00C0	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$00C1	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$00C2	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$00C3	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$00C4	$28D2			GOTO	SOK22LC
;math.ppas,767 :: 		
$00C5	$	SADD22LC:
;math.ppas,768 :: 		
$00C5	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$00C6	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$00C7	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$00C8	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$00C9	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$00CA	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$00CB	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$00CC	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$00CD	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$00CE	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$00CF	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$00D0	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$00D1	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$00D2	$	SOK22LC:
;math.ppas,784 :: 		
$00D2	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$00D3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$00D4	$28AF			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$00D5	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$00D6	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$00D7	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$00D8	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$00D9	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$00DA	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$00DB	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$00DC	$28EB			GOTO	SADD22L24
;math.ppas,797 :: 		
$00DD	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$00DE	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$00DF	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$00E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$00E1	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$00E2	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$00E3	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$00E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$00E5	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$00E6	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$00E7	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$00E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$00E9	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$00EA	$28F8			GOTO	SOK22L24
;math.ppas,812 :: 		
$00EB	$	SADD22L24:
;math.ppas,813 :: 		
$00EB	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$00EC	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$00ED	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$00EE	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$00EF	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$00F0	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$00F1	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$00F2	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$00F3	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$00F4	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$00F5	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$00F6	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$00F7	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$00F8	$	SOK22L24:
;math.ppas,829 :: 		
$00F8	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$00F9	$3007			MOVLW	7
;math.ppas,832 :: 		
$00FA	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$00FB	$	LOOPS3232D:
;math.ppas,834 :: 		
$00FB	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$00FC	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$00FD	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$00FE	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$00FF	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0100	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0101	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0102	$2911			GOTO	SADD22LD
;math.ppas,843 :: 		
$0103	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0104	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0105	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0106	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0107	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0108	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0109	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$010A	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$010B	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$010C	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$010D	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$010E	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$010F	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0110	$291E			GOTO	SOK22LD
;math.ppas,858 :: 		
$0111	$	SADD22LD:
;math.ppas,859 :: 		
$0111	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0112	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0113	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0114	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0115	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0116	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0117	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0118	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0119	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$011A	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$011B	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$011C	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$011D	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$011E	$	SOK22LD:
;math.ppas,876 :: 		
$011E	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$011F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0120	$28FB			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0121	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0122	$2931			GOTO	SOK22L
;math.ppas,882 :: 		
$0123	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0124	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0125	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0126	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0127	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0128	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0129	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$012A	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$012B	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$012C	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$012D	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$012E	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$012F	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0130	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0131	$	SOK22L:
;math.ppas,897 :: 		
$0131	$	math_L_9:
;math.ppas,898 :: 		
$0131	$0008			RETURN
$05F6	$	_comfrem:
$05F6	$1303			BCF	STATUS, RP1
$05F7	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$05F8	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$05F9	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$05FA	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$05FB	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$05FC	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$05FD	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$05FE	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$05FF	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0600	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0601	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0602	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0603	$	math_L_10:
;math.ppas,915 :: 		
$0603	$0008			RETURN
$0604	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0604	$1303			BCF	STATUS, RP1
$0605	$1283			BCF	STATUS, RP0
$0606	$080C			MOVF	PIR1, 0
$0607	$00F1			MOVWF	STACK_1
$0608	$3000			MOVLW	0
$0609	$1AF1			BTFSC	STACK_1, 5
$060A	$3001			MOVLW	1
$060B	$00F1			MOVWF	STACK_1
$060C	$0871			MOVF	STACK_1, 0
$060D	$00CC			MOVWF	_usart_data_ready_local_result
$060E	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$060E	$084C			MOVF	_usart_data_ready_local_result, 0
$060F	$00F0			MOVWF	STACK_0
$0610	$0008			RETURN
$05E3	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$05E3	$1303			BCF	STATUS, RP1
$05E4	$1283			BCF	STATUS, RP0
$05E5	$081A			MOVF	RCREG, 0
$05E6	$00CC			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$05E7	$0818			MOVF	RCSTA, 0
$05E8	$00F1			MOVWF	STACK_1
$05E9	$3000			MOVLW	0
$05EA	$18F1			BTFSC	STACK_1, 1
$05EB	$3001			MOVLW	1
$05EC	$00F1			MOVWF	STACK_1
$05ED	$0871			MOVF	STACK_1, 0
$05EE	$3A01			XORLW	1
$05EF	$1D03			BTFSS	STATUS, Z
$05F0	$2DF3			GOTO	USART_b75_L_21
$05F1	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$05F1	$1218			BCF	RCSTA, 4
$05F2	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$05F2	$	USART_b75_L_25:
$05F2	$1618			BSF	RCSTA, 4
$05F3	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$05F3	$	USART_b75_L_21:
$05F3	$	USART_b75_L_22:
$05F3	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$05F3	$084C			MOVF	_usart_read_local_result, 0
$05F4	$00F0			MOVWF	STACK_0
$05F5	$0008			RETURN
$0512	$	_mul_32x32_s:
$0512	$1303			BCF	STATUS, RP1
$0513	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$0514	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$0515	$	_IF_FIRST:
;math.ppas,1684 :: 		
$0515	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$0516	$2D24			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0517	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0517	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0518	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0519	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$051A	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$051B	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$051C	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$051D	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$051E	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$051F	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0520	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$0521	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$0522	$3081			MOVLW	129
;math.ppas,1711 :: 		
$0523	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$0524	$	_IF_SECOND:
;math.ppas,1715 :: 		
$0524	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$0525	$2D32			GOTO	_MULT
;math.ppas,1722 :: 		
$0526	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$0526	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0527	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0528	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0529	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$052A	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$052B	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$052C	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$052D	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$052E	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$052F	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0530	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$0531	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$0532	$	_MULT:
;math.ppas,1744 :: 		
$0532	$254D			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$0533	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$0534	$2D4C			GOTO	_EXIT
;math.ppas,1755 :: 		
$0535	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$0536	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0537	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0538	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0539	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$053A	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$053B	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$053C	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$053D	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$053E	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$053F	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0540	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$0541	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$0542	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$0543	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$0544	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$0545	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$0546	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0547	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0548	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0549	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$054A	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$054B	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$054C	$	_EXIT:
;math.ppas,1793 :: 		
$054C	$	math_L_14:
;math.ppas,1794 :: 		
$054C	$0008			RETURN
$05B1	$	_div_16x16_u:
$05B1	$1303			BCF	STATUS, RP1
$05B2	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$05B3	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$05B4	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$05B5	$3010			MOVLW	16
;math.ppas,113 :: 		
$05B6	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$05B7	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$05B8	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$05B9	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$05BA	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$05BB	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$05BC	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$05BD	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$05BE	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$05BF	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$05C0	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$05C1	$2DC9			GOTO	$+8
;math.ppas,125 :: 		
$05C2	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$05C3	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$05C4	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$05C5	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$05C6	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$05C7	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$05C8	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$05C9	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$05CA	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$05CB	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$05CC	$2DB7			GOTO	$-21
;math.ppas,136 :: 		
$05CD	$	math_L_3:
;math.ppas,137 :: 		
$05CD	$0008			RETURN
$01F4	$	_div_32x32_s:
$01F4	$1303			BCF	STATUS, RP1
$01F5	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$01F6	$	FXD3232S:
;math.ppas,929 :: 		
$01F6	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$01F7	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$01F8	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$01F9	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$01FA	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$01FB	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$01FC	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$01FD	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$01FE	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$01FF	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0200	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0201	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0202	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0203	$2A88			GOTO	END_ALL
;math.ppas,944 :: 		
$0204	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0205	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0206	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0207	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0208	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0209	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$020A	$2A16			GOTO	CA3232S
;math.ppas,955 :: 		
$020B	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$020C	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$020D	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$020E	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$020F	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0210	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0211	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0212	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0213	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0214	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0215	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0216	$	CA3232S:
;math.ppas,968 :: 		
$0216	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0217	$2A23			GOTO	C3232SX
;math.ppas,971 :: 		
$0218	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0219	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$021A	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$021B	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$021C	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$021D	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$021E	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$021F	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0220	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0221	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0222	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0223	$	C3232SX:
;math.ppas,984 :: 		
$0223	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0224	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0225	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0226	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0227	$2A44			GOTO	C3232SX1
;math.ppas,989 :: 		
$0228	$	C3232S:
;math.ppas,992 :: 		
$0228	$2004			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0229	$	C3232S2:
;math.ppas,996 :: 		
$0229	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$022A	$2A61			GOTO	C3232SX4
;math.ppas,998 :: 		
$022B	$	C3232SOK:
;math.ppas,999 :: 		
$022B	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$022C	$2A88			GOTO	END_ALL
;math.ppas,1001 :: 		
$022D	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$022E	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$022F	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0230	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0231	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0232	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0233	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0234	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0235	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0236	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0237	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0238	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0239	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$023A	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$023B	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$023C	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$023D	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$023E	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$023F	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0240	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0241	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0242	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0243	$2A88			GOTO	END_ALL
;math.ppas,1026 :: 		
$0244	$	C3232SX1:
;math.ppas,1027 :: 		
$0244	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0245	$2A5B			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0246	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0247	$2A55			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0248	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0249	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$024A	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$024B	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$024C	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$024D	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$024E	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$024F	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0250	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0251	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0252	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0253	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0254	$2A2B			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0255	$	C3232SX2:
;math.ppas,1045 :: 		
$0255	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0256	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0257	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0258	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0259	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$025A	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$025B	$	C3232SX3:
;math.ppas,1053 :: 		
$025B	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$025C	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$025D	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$025E	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$025F	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0260	$2A28			GOTO	C3232S
;math.ppas,1061 :: 		
$0261	$	C3232SX4:
;math.ppas,1062 :: 		
$0261	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0262	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0263	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0264	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0265	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0266	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0267	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0268	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0269	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$026A	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$026B	$2A2B			GOTO	C3232SOK
;math.ppas,1073 :: 		
$026C	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$026D	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$026E	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$026F	$2A2B			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0270	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0271	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0272	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0273	$2A2B			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0274	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0275	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0276	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0277	$2A2B			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0278	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0279	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$027A	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$027B	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$027C	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$027D	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$027E	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$027F	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0280	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0281	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0282	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0283	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0284	$2A2B			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0285	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0286	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0287	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0288	$	END_ALL:
;math.ppas,1102 :: 		
$0288	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0289	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$028A	$2A8C			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$028B	$25F6			CALL	_comfrem
;math.ppas,1108 :: 		
$028C	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$028C	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$028D	$	math_L_11:
;math.ppas,1111 :: 		
$028D	$0008			RETURN
$02FA	$	_vdelay_ms:
;delays.pbas,65 :: 		dim NumberOfCyc as dword
;delays.pbas,67 :: 		NumberOfCyc = Clock_kHz >> 2 ' this will be done by compiler, no asm will be genereated except that for assignment
$02FA	$30E8			MOVLW	232
$02FB	$1303			BCF	STATUS, RP1
$02FC	$1283			BCF	STATUS, RP0
$02FD	$00CE			MOVWF	_vdelay_ms_local_numberofcyc
$02FE	$3003			MOVLW	3
$02FF	$00CF			MOVWF	_vdelay_ms_local_numberofcyc+1
$0300	$01D0			CLRF	_vdelay_ms_local_numberofcyc+2
$0301	$01D1			CLRF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,68 :: 		NumberOfCyc = Time_ms * NumberOfCyc
$0302	$084C			MOVF	FARG_VDelay_ms, 0
$0303	$00F0			MOVWF	STACK_0
$0304	$084D			MOVF	FARG_VDelay_ms+1, 0
$0305	$00F1			MOVWF	STACK_0+1
$0306	$01F2			CLRF	STACK_0+2
$0307	$01F3			CLRF	STACK_0+3
$0308	$30E8			MOVLW	232
$0309	$00F4			MOVWF	STACK_4
$030A	$3003			MOVLW	3
$030B	$00F5			MOVWF	STACK_4+1
$030C	$3000			MOVLW	0
$030D	$00F6			MOVWF	STACK_4+2
$030E	$3000			MOVLW	0
$030F	$00F7			MOVWF	STACK_4+3
$0310	$254D			CALL	_mul_32x32_u
$0311	$0870			MOVF	STACK_0, 0
$0312	$00CE			MOVWF	_vdelay_ms_local_numberofcyc
$0313	$0871			MOVF	STACK_0+1, 0
$0314	$00CF			MOVWF	_vdelay_ms_local_numberofcyc+1
$0315	$0872			MOVF	STACK_0+2, 0
$0316	$00D0			MOVWF	_vdelay_ms_local_numberofcyc+2
$0317	$0873			MOVF	STACK_0+3, 0
$0318	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,69 :: 		if NumberOfCyc < 675 then
$0319	$3000			MOVLW	0
$031A	$0273			SUBWF	STACK_0+3, 0
$031B	$1D03			BTFSS	STATUS, Z
$031C	$2B27			GOTO	L_VDelay_ms_0
$031D	$3000			MOVLW	0
$031E	$0272			SUBWF	STACK_0+2, 0
$031F	$1D03			BTFSS	STATUS, Z
$0320	$2B27			GOTO	L_VDelay_ms_0
$0321	$3002			MOVLW	2
$0322	$0271			SUBWF	STACK_0+1, 0
$0323	$1D03			BTFSS	STATUS, Z
$0324	$2B27			GOTO	L_VDelay_ms_0
$0325	$30A3			MOVLW	163
$0326	$0270			SUBWF	STACK_0, 0
$0327	$	L_VDelay_ms_0:
$0327	$1803			BTFSC	STATUS, C
$0328	$2B2A			GOTO	delays_L_19
$0329	$	delays_L_18:
;delays.pbas,70 :: 		exit
$0329	$2B81			GOTO	delays_L_17
$032A	$	delays_L_19:
;delays.pbas,71 :: 		end if
$032A	$	delays_L_20:
;delays.pbas,72 :: 		NumberOfCyc = NumberOfCyc - 675
$032A	$30A3			MOVLW	163
$032B	$00F0			MOVWF	STACK_0
$032C	$3002			MOVLW	2
$032D	$00F1			MOVWF	STACK_0+1
$032E	$01F2			CLRF	STACK_0+2
$032F	$01F3			CLRF	STACK_0+3
$0330	$084E			MOVF	_vdelay_ms_local_numberofcyc, 0
$0331	$00F4			MOVWF	STACK_4
$0332	$084F			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$0333	$00F5			MOVWF	STACK_4+1
$0334	$0850			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$0335	$00F6			MOVWF	STACK_4+2
$0336	$0851			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0337	$00F7			MOVWF	STACK_4+3
$0338	$0870			MOVF	STACK_0, 0
$0339	$02F4			SUBWF	STACK_4, 1
$033A	$0871			MOVF	STACK_0+1, 0
$033B	$1C03			BTFSS	STATUS, C
$033C	$0F71			INCFSZ	STACK_0+1, 0
$033D	$02F5			SUBWF	STACK_4+1, 1
$033E	$0872			MOVF	STACK_0+2, 0
$033F	$1C03			BTFSS	STATUS, C
$0340	$0F72			INCFSZ	STACK_0+2, 0
$0341	$02F6			SUBWF	STACK_4+2, 1
$0342	$0873			MOVF	STACK_0+3, 0
$0343	$1C03			BTFSS	STATUS, C
$0344	$0F73			INCFSZ	STACK_0+3, 0
$0345	$02F7			SUBWF	STACK_4+3, 1
$0346	$0874			MOVF	STACK_4, 0
$0347	$00CE			MOVWF	_vdelay_ms_local_numberofcyc
$0348	$0875			MOVF	STACK_4+1, 0
$0349	$00CF			MOVWF	_vdelay_ms_local_numberofcyc+1
$034A	$0876			MOVF	STACK_4+2, 0
$034B	$00D0			MOVWF	_vdelay_ms_local_numberofcyc+2
$034C	$0877			MOVF	STACK_4+3, 0
$034D	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,73 :: 		NumberOfCyc = NumberOfCyc >> 5  ' Dec and While below take around 32 instructions
$034E	$3005			MOVLW	5
$034F	$00F0			MOVWF	STACK_0
$0350	$0874			MOVF	STACK_4, 0
$0351	$00CE			MOVWF	_vdelay_ms_local_numberofcyc
$0352	$0875			MOVF	STACK_4+1, 0
$0353	$00CF			MOVWF	_vdelay_ms_local_numberofcyc+1
$0354	$0876			MOVF	STACK_4+2, 0
$0355	$00D0			MOVWF	_vdelay_ms_local_numberofcyc+2
$0356	$0877			MOVF	STACK_4+3, 0
$0357	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+3
$0358	$0870			MOVF	STACK_0, 0
$0359	$	L_VDelay_ms_1:
$0359	$1903			BTFSC	STATUS, Z
$035A	$2B62			GOTO	L_VDelay_ms_2
$035B	$0CD1			RRF	_vdelay_ms_local_numberofcyc+3, 1
$035C	$0CD0			RRF	_vdelay_ms_local_numberofcyc+2, 1
$035D	$0CCF			RRF	_vdelay_ms_local_numberofcyc+1, 1
$035E	$0CCE			RRF	_vdelay_ms_local_numberofcyc, 1
$035F	$13D1			BCF	_vdelay_ms_local_numberofcyc+3, 7
$0360	$3FFF			ADDLW	255
$0361	$2B59			GOTO	L_VDelay_ms_1
$0362	$	L_VDelay_ms_2:
;delays.pbas,74 :: 		while ( Lo(NumberOfCyc) or Hi(NumberOfCyc) or Higher(NumberOfCyc) or Highest(NumberOfCyc) ) <> 0
$0362	$	delays_L_22:
$0362	$30FF			MOVLW	255
$0363	$054E			ANDWF	_vdelay_ms_local_numberofcyc, 0
$0364	$00F8			MOVWF	STACK_8
$0365	$084F			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$0366	$00F0			MOVWF	STACK_0
$0367	$0870			MOVF	STACK_0, 0
$0368	$04F8			IORWF	STACK_8, 1
$0369	$0850			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$036A	$00F0			MOVWF	STACK_0
$036B	$0851			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$036C	$00F1			MOVWF	STACK_0+1
$036D	$0870			MOVF	STACK_0, 0
$036E	$04F8			IORWF	STACK_8, 1
$036F	$0851			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0370	$00F0			MOVWF	STACK_0
$0371	$0870			MOVF	STACK_0, 0
$0372	$0478			IORWF	STACK_8, 0
$0373	$00F4			MOVWF	STACK_4
$0374	$0874			MOVF	STACK_4, 0
$0375	$3A00			XORLW	0
$0376	$1903			BTFSC	STATUS, Z
$0377	$2B81			GOTO	delays_L_23
;delays.pbas,75 :: 		Dec(NumberOfCyc)
$0378	$3001			MOVLW	1
$0379	$02CE			SUBWF	_vdelay_ms_local_numberofcyc, 1
$037A	$1C03			BTFSS	STATUS, C
$037B	$02CF			SUBWF	_vdelay_ms_local_numberofcyc+1, 1
$037C	$1C03			BTFSS	STATUS, C
$037D	$02D0			SUBWF	_vdelay_ms_local_numberofcyc+2, 1
$037E	$1C03			BTFSS	STATUS, C
$037F	$02D1			SUBWF	_vdelay_ms_local_numberofcyc+3, 1
$0380	$2B62			GOTO	delays_L_22
$0381	$	delays_L_23:
;delays.pbas,76 :: 		wend
$0381	$	delays_L_17:
$0381	$0008			RETURN
$0584	$	_div_16x16_s_l:
$0584	$1303			BCF	STATUS, RP1
$0585	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$0586	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$0587	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$0588	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$0589	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$058A	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$058B	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$058C	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$058D	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$058E	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$058F	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0590	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$0591	$300F			MOVLW	15
;math.ppas,307 :: 		
$0592	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0593	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$0594	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$0595	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$0596	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$0597	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$0598	$2D9F			GOTO	$+7
;math.ppas,315 :: 		
$0599	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$059A	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$059B	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$059C	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$059D	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$059E	$2DA4			GOTO	$+6
;math.ppas,322 :: 		
$059F	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$05A0	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$05A1	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$05A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$05A3	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$05A4	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$05A5	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$05A6	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$05A7	$2D93			GOTO	$-20
;math.ppas,334 :: 		
$05A8	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$05A9	$2DB0			GOTO	$+7
;math.ppas,336 :: 		
$05AA	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$05AB	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$05AC	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$05AD	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$05AE	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$05AF	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$05B0	$	math_L_6:
;math.ppas,343 :: 		
$05B0	$0008			RETURN
$0440	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$0440	$1303			BCF	STATUS, RP1
$0441	$1283			BCF	STATUS, RP0
$0442	$01C1			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$0443	$01C2			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$0444	$01C5			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$0445	$0840			MOVF	FARG_Usart_Read_Text+1, 0
$0446	$0084			MOVWF	FSR
$0447	$0800			MOVF	INDF, 0
$0448	$00C4			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$0449	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$0449	$2604			CALL	_usart_data_ready
$044A	$0870			MOVF	STACK_0, 0
$044B	$3A00			XORLW	0
$044C	$1903			BTFSC	STATUS, Z
$044D	$2C79			GOTO	USART_b75_L_34
$044E	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$044E	$25E3			CALL	_usart_read
$044F	$0870			MOVF	STACK_0, 0
$0450	$00C3			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$0451	$0841			MOVF	_usart_read_text_local_i, 0
$0452	$073F			ADDWF	FARG_Usart_Read_Text, 0
$0453	$00F1			MOVWF	STACK_1
$0454	$0871			MOVF	STACK_1, 0
$0455	$0084			MOVWF	FSR
$0456	$0871			MOVF	STACK_1, 0
$0457	$0084			MOVWF	FSR
$0458	$0870			MOVF	STACK_0, 0
$0459	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$045A	$0843			MOVF	_usart_read_text_local_data, 0
$045B	$0644			XORWF	_usart_read_text_local_data2, 0
$045C	$1D03			BTFSS	STATUS, Z
$045D	$2C63			GOTO	USART_b75_L_37
$045E	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$045E	$0842			MOVF	_usart_read_text_local_j, 0
$045F	$0241			SUBWF	_usart_read_text_local_i, 0
$0460	$00C5			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$0461	$0AC2			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$0462	$2C65			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$0463	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$0463	$01C2			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$0464	$01C5			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$0465	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$0465	$0842			MOVF	_usart_read_text_local_j, 0
$0466	$0740			ADDWF	FARG_Usart_Read_Text+1, 0
$0467	$0084			MOVWF	FSR
$0468	$0800			MOVF	INDF, 0
$0469	$00F1			MOVWF	STACK_1
$046A	$0871			MOVF	STACK_1, 0
$046B	$00C4			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$046C	$0871			MOVF	STACK_1, 0
$046D	$3A00			XORLW	0
$046E	$1D03			BTFSS	STATUS, Z
$046F	$2C71			GOTO	USART_b75_L_40
$0470	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$0470	$2C7A			GOTO	USART_b75_L_30
$0471	$	USART_b75_L_40:
$0471	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$0471	$0AC1			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$0472	$0841			MOVF	_usart_read_text_local_i, 0
$0473	$3C14			SUBLW	20
$0474	$1803			BTFSC	STATUS, C
$0475	$2C79			GOTO	USART_b75_L_43
$0476	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$0476	$3013			MOVLW	19
$0477	$00C5			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0478	$2C7A			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0479	$	USART_b75_L_43:
$0479	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0479	$	USART_b75_L_34:
$0479	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0479	$2C49			GOTO	USART_b75_L_29
$047A	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$047A	$0845			MOVF	_usart_read_text_local_lasti, 0
$047B	$073F			ADDWF	FARG_Usart_Read_Text, 0
$047C	$00F0			MOVWF	STACK_0
$047D	$0870			MOVF	STACK_0, 0
$047E	$0084			MOVWF	FSR
$047F	$0870			MOVF	STACK_0, 0
$0480	$0084			MOVWF	FSR
$0481	$0180			CLRF	INDF, 1
$0482	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$0482	$0008			RETURN
$0132	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$0132	$1303			BCF	STATUS, RP1
$0133	$1283			BCF	STATUS, RP0
$0134	$01C0			CLRF	_strtoint_local_result
$0135	$01C1			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0136	$3010			MOVLW	16
$0137	$00C4			MOVWF	_strtoint_local_ep
$0138	$3027			MOVLW	39
$0139	$00C5			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$013A	$01C2			CLRF	_strtoint_local_i
$013B	$01C3			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$013C	$01C8			CLRF	_strtoint_local_tmp
$013D	$01C9			CLRF	_strtoint_local_tmp+1
$013E	$01CA			CLRF	_strtoint_local_tmp+2
$013F	$01CB			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$0140	$01C6			CLRF	_strtoint_local_negative
$0141	$01C7			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$0142	$	conv_L_172:
$0142	$0842			MOVF	_strtoint_local_i, 0
$0143	$073F			ADDWF	FARG_StrToInt, 0
$0144	$0084			MOVWF	FSR
$0145	$0800			MOVF	INDF, 0
$0146	$00F4			MOVWF	STACK_4
$0147	$0874			MOVF	STACK_4, 0
$0148	$3A00			XORLW	0
$0149	$1903			BTFSC	STATUS, Z
$014A	$29AE			GOTO	conv_L_173
;conv.ppas,355 :: 		
$014B	$0842			MOVF	_strtoint_local_i, 0
$014C	$073F			ADDWF	FARG_StrToInt, 0
$014D	$0084			MOVWF	FSR
$014E	$0800			MOVF	INDF, 0
$014F	$00F4			MOVWF	STACK_4
$0150	$0874			MOVF	STACK_4, 0
$0151	$3A2D			XORLW	45
$0152	$1D03			BTFSS	STATUS, Z
$0153	$295B			GOTO	conv_L_177
$0154	$	conv_L_176:
;conv.ppas,357 :: 		
$0154	$30FF			MOVLW	255
$0155	$00C6			MOVWF	_strtoint_local_negative
$0156	$01C7			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0157	$0AC2			INCF	_strtoint_local_i, 1
$0158	$1903			BTFSC	STATUS, Z
$0159	$0AC3			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$015A	$2942			GOTO	conv_L_172
;conv.ppas,360 :: 		
$015B	$	conv_L_177:
$015B	$	conv_L_178:
;conv.ppas,361 :: 		
$015B	$0842			MOVF	_strtoint_local_i, 0
$015C	$073F			ADDWF	FARG_StrToInt, 0
$015D	$0084			MOVWF	FSR
$015E	$0800			MOVF	INDF, 0
$015F	$00F4			MOVWF	STACK_4
$0160	$0874			MOVF	STACK_4, 0
$0161	$3A20			XORLW	32
$0162	$1903			BTFSC	STATUS, Z
$0163	$299E			GOTO	conv_L_180
$0164	$	conv_L_179:
;conv.ppas,362 :: 		
$0164	$0842			MOVF	_strtoint_local_i, 0
$0165	$073F			ADDWF	FARG_StrToInt, 0
$0166	$0084			MOVWF	FSR
$0167	$0800			MOVF	INDF, 0
$0168	$00F0			MOVWF	STACK_0
$0169	$3030			MOVLW	48
$016A	$00F8			MOVWF	STACK_8
$016B	$01F9			CLRF	STACK_8+1
$016C	$01FA			CLRF	STACK_8+2
$016D	$01FB			CLRF	STACK_8+3
$016E	$0870			MOVF	STACK_0, 0
$016F	$00F4			MOVWF	STACK_4
$0170	$01F5			CLRF	STACK_4+1
$0171	$01F6			CLRF	STACK_4+2
$0172	$01F7			CLRF	STACK_4+3
$0173	$0874			MOVF	STACK_4, 0
$0174	$00F0			MOVWF	STACK_0
$0175	$0875			MOVF	STACK_4+1, 0
$0176	$00F1			MOVWF	STACK_0+1
$0177	$0876			MOVF	STACK_4+2, 0
$0178	$00F2			MOVWF	STACK_0+2
$0179	$0877			MOVF	STACK_4+3, 0
$017A	$00F3			MOVWF	STACK_0+3
$017B	$0878			MOVF	STACK_8, 0
$017C	$02F0			SUBWF	STACK_0, 1
$017D	$0879			MOVF	STACK_8+1, 0
$017E	$1C03			BTFSS	STATUS, C
$017F	$0F79			INCFSZ	STACK_8+1, 0
$0180	$02F1			SUBWF	STACK_0+1, 1
$0181	$087A			MOVF	STACK_8+2, 0
$0182	$1C03			BTFSS	STATUS, C
$0183	$0F7A			INCFSZ	STACK_8+2, 0
$0184	$02F2			SUBWF	STACK_0+2, 1
$0185	$087B			MOVF	STACK_8+3, 0
$0186	$1C03			BTFSS	STATUS, C
$0187	$0F7B			INCFSZ	STACK_8+3, 0
$0188	$02F3			SUBWF	STACK_0+3, 1
$0189	$0844			MOVF	_strtoint_local_ep, 0
$018A	$00F4			MOVWF	STACK_4
$018B	$0845			MOVF	_strtoint_local_ep+1, 0
$018C	$00F5			MOVWF	STACK_4+1
$018D	$01F6			CLRF	STACK_4+2
$018E	$01F7			CLRF	STACK_4+3
$018F	$2512			CALL	_mul_32x32_s
$0190	$0870			MOVF	STACK_0, 0
$0191	$07C8			ADDWF	_strtoint_local_tmp, 1
$0192	$0871			MOVF	STACK_0+1, 0
$0193	$1803			BTFSC	STATUS, C
$0194	$0F71			INCFSZ	STACK_0+1, 0
$0195	$07C9			ADDWF	_strtoint_local_tmp+1, 1
$0196	$0872			MOVF	STACK_0+2, 0
$0197	$1803			BTFSC	STATUS, C
$0198	$0F72			INCFSZ	STACK_0+2, 0
$0199	$07CA			ADDWF	_strtoint_local_tmp+2, 1
$019A	$0873			MOVF	STACK_0+3, 0
$019B	$1803			BTFSC	STATUS, C
$019C	$0F73			INCFSZ	STACK_0+3, 0
$019D	$07CB			ADDWF	_strtoint_local_tmp+3, 1
$019E	$	conv_L_180:
$019E	$	conv_L_181:
;conv.ppas,363 :: 		
$019E	$300A			MOVLW	10
$019F	$00F4			MOVWF	STACK_4
$01A0	$01F5			CLRF	STACK_4+1
$01A1	$0844			MOVF	_strtoint_local_ep, 0
$01A2	$00F0			MOVWF	STACK_0
$01A3	$0845			MOVF	_strtoint_local_ep+1, 0
$01A4	$00F1			MOVWF	STACK_0+1
$01A5	$25B1			CALL	_div_16x16_u
$01A6	$0870			MOVF	STACK_0, 0
$01A7	$00C4			MOVWF	_strtoint_local_ep
$01A8	$0871			MOVF	STACK_0+1, 0
$01A9	$00C5			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$01AA	$0AC2			INCF	_strtoint_local_i, 1
$01AB	$1903			BTFSC	STATUS, Z
$01AC	$0AC3			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$01AD	$2942			GOTO	conv_L_172
$01AE	$	conv_L_173:
;conv.ppas,370 :: 		
$01AE	$0846			MOVF	_strtoint_local_negative, 0
$01AF	$0447			IORWF	_strtoint_local_negative+1, 0
$01B0	$1903			BTFSC	STATUS, Z
$01B1	$29B6			GOTO	conv_L_183
$01B2	$	conv_L_182:
$01B2	$3006			MOVLW	6
$01B3	$00C4			MOVWF	_strtoint_local_ep
$01B4	$01C5			CLRF	_strtoint_local_ep+1
$01B5	$29B9			GOTO	conv_L_184
;conv.ppas,371 :: 		
$01B6	$	conv_L_183:
$01B6	$3005			MOVLW	5
$01B7	$00C4			MOVWF	_strtoint_local_ep
$01B8	$01C5			CLRF	_strtoint_local_ep+1
$01B9	$	conv_L_184:
;conv.ppas,373 :: 		
$01B9	$	conv_L_186:
$01B9	$0843			MOVF	_strtoint_local_i+1, 0
$01BA	$0645			XORWF	_strtoint_local_ep+1, 0
$01BB	$1D03			BTFSS	STATUS, Z
$01BC	$29BF			GOTO	L_StrToInt_20
$01BD	$0844			MOVF	_strtoint_local_ep, 0
$01BE	$0642			XORWF	_strtoint_local_i, 0
$01BF	$	L_StrToInt_20:
$01BF	$1903			BTFSC	STATUS, Z
$01C0	$29DB			GOTO	conv_L_187
;conv.ppas,375 :: 		
$01C1	$300A			MOVLW	10
$01C2	$00F4			MOVWF	STACK_4
$01C3	$01F5			CLRF	STACK_4+1
$01C4	$01F6			CLRF	STACK_4+2
$01C5	$01F7			CLRF	STACK_4+3
$01C6	$0848			MOVF	_strtoint_local_tmp, 0
$01C7	$00F0			MOVWF	STACK_0
$01C8	$0849			MOVF	_strtoint_local_tmp+1, 0
$01C9	$00F1			MOVWF	STACK_0+1
$01CA	$084A			MOVF	_strtoint_local_tmp+2, 0
$01CB	$00F2			MOVWF	STACK_0+2
$01CC	$084B			MOVF	_strtoint_local_tmp+3, 0
$01CD	$00F3			MOVWF	STACK_0+3
$01CE	$21F4			CALL	_div_32x32_s
$01CF	$0870			MOVF	STACK_0, 0
$01D0	$00C8			MOVWF	_strtoint_local_tmp
$01D1	$0871			MOVF	STACK_0+1, 0
$01D2	$00C9			MOVWF	_strtoint_local_tmp+1
$01D3	$0872			MOVF	STACK_0+2, 0
$01D4	$00CA			MOVWF	_strtoint_local_tmp+2
$01D5	$0873			MOVF	STACK_0+3, 0
$01D6	$00CB			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$01D7	$0AC2			INCF	_strtoint_local_i, 1
$01D8	$1903			BTFSC	STATUS, Z
$01D9	$0AC3			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$01DA	$29B9			GOTO	conv_L_186
$01DB	$	conv_L_187:
;conv.ppas,380 :: 		
$01DB	$0848			MOVF	_strtoint_local_tmp, 0
$01DC	$00C0			MOVWF	_strtoint_local_result
$01DD	$0849			MOVF	_strtoint_local_tmp+1, 0
$01DE	$00C1			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$01DF	$3000			MOVLW	0
$01E0	$0647			XORWF	_strtoint_local_negative+1, 0
$01E1	$1D03			BTFSS	STATUS, Z
$01E2	$29E5			GOTO	L_StrToInt_21
$01E3	$30FF			MOVLW	255
$01E4	$0646			XORWF	_strtoint_local_negative, 0
$01E5	$	L_StrToInt_21:
$01E5	$1D03			BTFSS	STATUS, Z
$01E6	$29EF			GOTO	conv_L_191
$01E7	$	conv_L_190:
;conv.ppas,383 :: 		
$01E7	$0840			MOVF	_strtoint_local_result, 0
$01E8	$3C00			SUBLW	0
$01E9	$00C0			MOVWF	_strtoint_local_result
$01EA	$0841			MOVF	_strtoint_local_result+1, 0
$01EB	$1C03			BTFSS	STATUS, C
$01EC	$3F01			ADDLW	1
$01ED	$01C1			CLRF	_strtoint_local_result+1
$01EE	$02C1			SUBWF	_strtoint_local_result+1, 1
$01EF	$	conv_L_191:
$01EF	$	conv_L_192:
$01EF	$	conv_L_170:
;conv.ppas,384 :: 		
$01EF	$0840			MOVF	_strtoint_local_result, 0
$01F0	$00F0			MOVWF	STACK_0
$01F1	$0841			MOVF	_strtoint_local_result+1, 0
$01F2	$00F1			MOVWF	STACK_0+1
$01F3	$0008			RETURN
$04CC	$	_strcmp:
;StringsLib.ppas,172 :: 		
;StringsLib.ppas,173 :: 		
$04CC	$1303			BCF	STATUS, RP1
$04CD	$1283			BCF	STATUS, RP0
$04CE	$01C3			CLRF	_strcmp_local_i, 1
;StringsLib.ppas,174 :: 		
$04CF	$083F			MOVF	FARG_strcmp, 0
$04D0	$0084			MOVWF	FSR
$04D1	$0800			MOVF	INDF, 0
$04D2	$00C1			MOVWF	_strcmp_local_result
$04D3	$01C2			CLRF	_strcmp_local_result+1
;StringsLib.ppas,175 :: 		
$04D4	$0840			MOVF	FARG_strcmp+1, 0
$04D5	$0084			MOVWF	FSR
$04D6	$0800			MOVF	INDF, 0
$04D7	$00F0			MOVWF	STACK_0
;StringsLib.ppas,176 :: 		
$04D8	$3000			MOVLW	0
$04D9	$00C2			MOVWF	_strcmp_local_result+1
$04DA	$0870			MOVF	STACK_0, 0
$04DB	$02C1			SUBWF	_strcmp_local_result, 1
$04DC	$1C03			BTFSS	STATUS, C
$04DD	$03C2			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,177 :: 		
$04DE	$	StringsLib_L_77:
$04DE	$3000			MOVLW	0
$04DF	$0642			XORWF	_strcmp_local_result+1, 0
$04E0	$1D03			BTFSS	STATUS, Z
$04E1	$2CE4			GOTO	L_strcmp_8
$04E2	$3000			MOVLW	0
$04E3	$0641			XORWF	_strcmp_local_result, 0
$04E4	$	L_strcmp_8:
$04E4	$30FF			MOVLW	255
$04E5	$1D03			BTFSS	STATUS, Z
$04E6	$3000			MOVLW	0
$04E7	$00F3			MOVWF	STACK_3
$04E8	$0843			MOVF	_strcmp_local_i, 0
$04E9	$073F			ADDWF	FARG_strcmp, 0
$04EA	$0084			MOVWF	FSR
$04EB	$0800			MOVF	INDF, 0
$04EC	$00F2			MOVWF	STACK_2
$04ED	$0872			MOVF	STACK_2, 0
$04EE	$3A00			XORLW	0
$04EF	$30FF			MOVLW	255
$04F0	$1903			BTFSC	STATUS, Z
$04F1	$3000			MOVLW	0
$04F2	$00F0			MOVWF	STACK_0
$04F3	$0873			MOVF	STACK_3, 0
$04F4	$05F0			ANDWF	STACK_0, 1
$04F5	$1903			BTFSC	STATUS, Z
$04F6	$2D0D			GOTO	StringsLib_L_78
;StringsLib.ppas,179 :: 		
$04F7	$0A43			INCF	_strcmp_local_i, 0
$04F8	$00F0			MOVWF	STACK_0
$04F9	$0870			MOVF	STACK_0, 0
$04FA	$00C3			MOVWF	_strcmp_local_i
;StringsLib.ppas,180 :: 		
$04FB	$0870			MOVF	STACK_0, 0
$04FC	$073F			ADDWF	FARG_strcmp, 0
$04FD	$0084			MOVWF	FSR
$04FE	$0800			MOVF	INDF, 0
$04FF	$00C1			MOVWF	_strcmp_local_result
$0500	$01C2			CLRF	_strcmp_local_result+1
;StringsLib.ppas,181 :: 		
$0501	$0870			MOVF	STACK_0, 0
$0502	$0740			ADDWF	FARG_strcmp+1, 0
$0503	$0084			MOVWF	FSR
$0504	$0800			MOVF	INDF, 0
$0505	$00F0			MOVWF	STACK_0
;StringsLib.ppas,182 :: 		
$0506	$3000			MOVLW	0
$0507	$00C2			MOVWF	_strcmp_local_result+1
$0508	$0870			MOVF	STACK_0, 0
$0509	$02C1			SUBWF	_strcmp_local_result, 1
$050A	$1C03			BTFSS	STATUS, C
$050B	$03C2			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,183 :: 		
$050C	$2CDE			GOTO	StringsLib_L_77
$050D	$	StringsLib_L_78:
$050D	$	StringsLib_L_75:
;StringsLib.ppas,184 :: 		
$050D	$0841			MOVF	_strcmp_local_result, 0
$050E	$00F0			MOVWF	STACK_0
$050F	$0842			MOVF	_strcmp_local_result+1, 0
$0510	$00F1			MOVWF	STACK_0+1
$0511	$0008			RETURN
$0382	$	_giramotor:
;DriverDeControle.pbas,15 :: 		sub procedure giraMotor()
;DriverDeControle.pbas,17 :: 		for x = 1 to ciclo
$0382	$3001			MOVLW	1
$0383	$1303			BCF	STATUS, RP1
$0384	$1283			BCF	STATUS, RP0
$0385	$00A1			MOVWF	_x
$0386	$01A2			CLRF	_x+1
$0387	$	DriverDeControle_L_1:
$0387	$3080			MOVLW	128
$0388	$0624			XORWF	_ciclo+1, 0
$0389	$00F0			MOVWF	STACK_0
$038A	$3080			MOVLW	128
$038B	$0622			XORWF	_x+1, 0
$038C	$0270			SUBWF	STACK_0, 0
$038D	$1D03			BTFSS	STATUS, Z
$038E	$2B91			GOTO	L_giraMotor_0
$038F	$0821			MOVF	_x, 0
$0390	$0223			SUBWF	_ciclo, 0
$0391	$	L_giraMotor_0:
$0391	$1C03			BTFSS	STATUS, C
$0392	$2BE4			GOTO	DriverDeControle_L_4
;DriverDeControle.pbas,19 :: 		if motor = 1 then
$0393	$3000			MOVLW	0
$0394	$0626			XORWF	_motor+1, 0
$0395	$1D03			BTFSS	STATUS, Z
$0396	$2B99			GOTO	L_giraMotor_1
$0397	$3001			MOVLW	1
$0398	$0625			XORWF	_motor, 0
$0399	$	L_giraMotor_1:
$0399	$1D03			BTFSS	STATUS, Z
$039A	$2BD8			GOTO	DriverDeControle_L_6
$039B	$	DriverDeControle_L_5:
;DriverDeControle.pbas,20 :: 		if s1 = true then
$039B	$0827			MOVF	_s1, 0
$039C	$3AFF			XORLW	255
$039D	$1D03			BTFSS	STATUS, Z
$039E	$2BBC			GOTO	DriverDeControle_L_9
$039F	$	DriverDeControle_L_8:
;DriverDeControle.pbas,21 :: 		PORTC=%00000001 vdelay_ms(tmpOn)
$039F	$3001			MOVLW	1
$03A0	$0087			MOVWF	PORTC
$03A1	$0828			MOVF	_tmpon, 0
$03A2	$00CC			MOVWF	FARG_VDelay_ms
$03A3	$0829			MOVF	_tmpon+1, 0
$03A4	$00CD			MOVWF	FARG_VDelay_ms+1
$03A5	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,22 :: 		PORTC=%00000010 vdelay_ms(tmpOn)
$03A6	$3002			MOVLW	2
$03A7	$0087			MOVWF	PORTC
$03A8	$0828			MOVF	_tmpon, 0
$03A9	$00CC			MOVWF	FARG_VDelay_ms
$03AA	$0829			MOVF	_tmpon+1, 0
$03AB	$00CD			MOVWF	FARG_VDelay_ms+1
$03AC	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,23 :: 		PORTC=%00000100 vdelay_ms(tmpOn)
$03AD	$3004			MOVLW	4
$03AE	$0087			MOVWF	PORTC
$03AF	$0828			MOVF	_tmpon, 0
$03B0	$00CC			MOVWF	FARG_VDelay_ms
$03B1	$0829			MOVF	_tmpon+1, 0
$03B2	$00CD			MOVWF	FARG_VDelay_ms+1
$03B3	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,24 :: 		PORTC=%00001000 vdelay_ms(tmpOn)
$03B4	$3008			MOVLW	8
$03B5	$0087			MOVWF	PORTC
$03B6	$0828			MOVF	_tmpon, 0
$03B7	$00CC			MOVWF	FARG_VDelay_ms
$03B8	$0829			MOVF	_tmpon+1, 0
$03B9	$00CD			MOVWF	FARG_VDelay_ms+1
$03BA	$22FA			CALL	_vdelay_ms
$03BB	$2BD8			GOTO	DriverDeControle_L_10
;DriverDeControle.pbas,25 :: 		else
$03BC	$	DriverDeControle_L_9:
;DriverDeControle.pbas,26 :: 		PORTC=%00001000 vdelay_ms(tmpOn)
$03BC	$3008			MOVLW	8
$03BD	$0087			MOVWF	PORTC
$03BE	$0828			MOVF	_tmpon, 0
$03BF	$00CC			MOVWF	FARG_VDelay_ms
$03C0	$0829			MOVF	_tmpon+1, 0
$03C1	$00CD			MOVWF	FARG_VDelay_ms+1
$03C2	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,27 :: 		PORTC=%00000100 vdelay_ms(tmpOn)
$03C3	$3004			MOVLW	4
$03C4	$0087			MOVWF	PORTC
$03C5	$0828			MOVF	_tmpon, 0
$03C6	$00CC			MOVWF	FARG_VDelay_ms
$03C7	$0829			MOVF	_tmpon+1, 0
$03C8	$00CD			MOVWF	FARG_VDelay_ms+1
$03C9	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,28 :: 		PORTC=%00000010 vdelay_ms(tmpOn)
$03CA	$3002			MOVLW	2
$03CB	$0087			MOVWF	PORTC
$03CC	$0828			MOVF	_tmpon, 0
$03CD	$00CC			MOVWF	FARG_VDelay_ms
$03CE	$0829			MOVF	_tmpon+1, 0
$03CF	$00CD			MOVWF	FARG_VDelay_ms+1
$03D0	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,29 :: 		PORTC=%00000001 vdelay_ms(tmpOn)
$03D1	$3001			MOVLW	1
$03D2	$0087			MOVWF	PORTC
$03D3	$0828			MOVF	_tmpon, 0
$03D4	$00CC			MOVWF	FARG_VDelay_ms
$03D5	$0829			MOVF	_tmpon+1, 0
$03D6	$00CD			MOVWF	FARG_VDelay_ms+1
$03D7	$22FA			CALL	_vdelay_ms
;DriverDeControle.pbas,30 :: 		end if
$03D8	$	DriverDeControle_L_10:
$03D8	$	DriverDeControle_L_6:
;DriverDeControle.pbas,31 :: 		end if
$03D8	$	DriverDeControle_L_7:
;DriverDeControle.pbas,33 :: 		next x
$03D8	$0822			MOVF	_x+1, 0
$03D9	$0624			XORWF	_ciclo+1, 0
$03DA	$1D03			BTFSS	STATUS, Z
$03DB	$2BDE			GOTO	L_giraMotor_2
$03DC	$0823			MOVF	_ciclo, 0
$03DD	$0621			XORWF	_x, 0
$03DE	$	L_giraMotor_2:
$03DE	$1903			BTFSC	STATUS, Z
$03DF	$2BE4			GOTO	DriverDeControle_L_4
$03E0	$	DriverDeControle_L_2:
$03E0	$0AA1			INCF	_x, 1
$03E1	$1903			BTFSC	STATUS, Z
$03E2	$0AA2			INCF	_x+1, 1
$03E3	$2B87			GOTO	DriverDeControle_L_1
$03E4	$	DriverDeControle_L_4:
;DriverDeControle.pbas,35 :: 		PORTC=0
$03E4	$0187			CLRF	PORTC, 1
$03E5	$	DriverDeControle_L_0:
$03E5	$0008			RETURN
$05CE	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$05CE	$	USART_b75_L_1:
$05CE	$1303			BCF	STATUS, RP1
$05CF	$1683			BSF	STATUS, RP0
$05D0	$1698			BSF	TXSTA, 5
$05D1	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$05D1	$3090			MOVLW	144
$05D2	$1283			BCF	STATUS, RP0
$05D3	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$05D4	$	USART_b75_L_3:
$05D4	$1683			BSF	STATUS, RP0
$05D5	$1686			BSF	TRISB, 5
$05D6	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$05D6	$	USART_b75_L_5:
$05D6	$1786			BSF	TRISB, 7
$05D7	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$05D7	$	USART_b75_L_8:
$05D7	$1283			BCF	STATUS, RP0
$05D8	$080C			MOVF	PIR1, 0
$05D9	$00F1			MOVWF	STACK_1
$05DA	$3000			MOVLW	0
$05DB	$1AF1			BTFSC	STACK_1, 5
$05DC	$3001			MOVLW	1
$05DD	$00F1			MOVWF	STACK_1
$05DE	$0871			MOVF	STACK_1, 0
$05DF	$3A01			XORLW	1
$05E0	$1903			BTFSC	STATUS, Z
$05E1	$2DD7			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$05E2	$	USART_b75_L_9:
$05E2	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$05E2	$0008			RETURN
$03E6	$	_div_16x16_s:
$03E6	$1303			BCF	STATUS, RP1
$03E7	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$03E8	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$03E9	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$03EA	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$03EB	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$03EC	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$03ED	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$03EE	$3400			RETLW	0
;math.ppas,356 :: 		
$03EF	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$03F0	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$03F1	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$03F2	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$03F3	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$03F4	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$03F5	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$03F6	$2BFC			GOTO	$+6
;math.ppas,367 :: 		
$03F7	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$03F8	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$03F9	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$03FA	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$03FB	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$03FC	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$03FD	$2C03			GOTO	$+6
;math.ppas,376 :: 		
$03FE	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$03FF	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$0400	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$0401	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$0402	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$0403	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$0404	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$0405	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$0406	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$0407	$2C18			GOTO	$+17
;math.ppas,388 :: 		
$0408	$2584			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$0409	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$040A	$2C2B			GOTO	$+33
;math.ppas,393 :: 		
$040B	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$040C	$3400			RETLW	0
;math.ppas,396 :: 		
$040D	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$040E	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$040F	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$0410	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$0411	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$0412	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$0413	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$0414	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$0415	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$0416	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$0417	$3400			RETLW	0
;math.ppas,410 :: 		
$0418	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$0419	$2C27			GOTO	$+14
;math.ppas,412 :: 		
$041A	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$041B	$2C23			GOTO	$+8
;math.ppas,414 :: 		
$041C	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$041D	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$041E	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$041F	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$0420	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$0421	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$0422	$2C0B			GOTO	$-23
;math.ppas,421 :: 		
$0423	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$0424	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$0425	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$0426	$3400			RETLW	0
;math.ppas,426 :: 		
$0427	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$0428	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$0429	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$042A	$2C08			GOTO	$-34
;math.ppas,431 :: 		
$042B	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$042C	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$042D	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$042E	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$042F	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0430	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$0431	$2C0B			GOTO	$-38
;math.ppas,438 :: 		
$0432	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$0433	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$0434	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$0435	$2C0B			GOTO	$-42
;math.ppas,442 :: 		
$0436	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$0437	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$0438	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$0439	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$043A	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$043B	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$043C	$2C0B			GOTO	$-49
;math.ppas,449 :: 		
$043D	$0000			NOP
;math.ppas,450 :: 		
$043E	$34FF			RETLW	255
;math.ppas,451 :: 		
$043F	$	math_L_7:
;math.ppas,452 :: 		
$043F	$0008			RETURN
$0483	$	_mul_16x16_s:
$0483	$1303			BCF	STATUS, RP1
$0484	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$0485	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$0486	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$0487	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$0488	$3080			MOVLW	128
;math.ppas,210 :: 		
$0489	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$048A	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$048B	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$048C	$2C93			GOTO	$+7
;math.ppas,215 :: 		
$048D	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$048E	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$048F	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$0490	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$0491	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$0492	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$0493	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$0494	$2C9B			GOTO	$+7
;math.ppas,224 :: 		
$0495	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$0496	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$0497	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$0498	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$0499	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$049A	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$049B	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$049C	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$049D	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$049E	$2CA8			GOTO	$+10
;math.ppas,236 :: 		
$049F	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$04A0	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$04A1	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$04A2	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$04A3	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$04A4	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$04A5	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$04A6	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$04A7	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$04A8	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$04A9	$2CB0			GOTO	$+7
;math.ppas,249 :: 		
$04AA	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$04AB	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$04AC	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$04AD	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$04AE	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$04AF	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$04B0	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$04B1	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$04B2	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$04B3	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$04B4	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$04B5	$2C9B			GOTO	$-26
;math.ppas,263 :: 		
$04B6	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$04B7	$2CC3			GOTO	$+12
;math.ppas,266 :: 		
$04B8	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$04B9	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$04BA	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$04BB	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$04BC	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$04BD	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$04BE	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$04BF	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$04C0	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$04C1	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$04C2	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$04C3	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$04C4	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$04C5	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$04C6	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$04C7	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$04C8	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$04C9	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$04CA	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$04CB	$	math_L_5:
;math.ppas,288 :: 		
$04CB	$0008			RETURN
$028E	$	_main:
;DriverDeControle.pbas,39 :: 		main:
$028E	$	_main_main:
;DriverDeControle.pbas,40 :: 		TRISA=%11111110
$028E	$30FE			MOVLW	254
$028F	$1303			BCF	STATUS, RP1
$0290	$1683			BSF	STATUS, RP0
$0291	$0085			MOVWF	TRISA
;DriverDeControle.pbas,41 :: 		TRISB=%01111111
$0292	$307F			MOVLW	127
$0293	$0086			MOVWF	TRISB
;DriverDeControle.pbas,42 :: 		TRISC=%00000000
$0294	$0187			CLRF	TRISC, 1
;DriverDeControle.pbas,43 :: 		INTCON=%00000000
$0295	$018B			CLRF	INTCON, 1
;DriverDeControle.pbas,44 :: 		ANSEL=%00000000
$0296	$1703			BSF	STATUS, RP1
$0297	$1283			BCF	STATUS, RP0
$0298	$019E			CLRF	ANSEL, 1
;DriverDeControle.pbas,45 :: 		ANSELH=%00000000
$0299	$019F			CLRF	ANSELH, 1
;DriverDeControle.pbas,46 :: 		PORTC=0
$029A	$1303			BCF	STATUS, RP1
$029B	$0187			CLRF	PORTC, 1
;DriverDeControle.pbas,48 :: 		Usart_Init(9600)
$029C	$3019			MOVLW	25
$029D	$1683			BSF	STATUS, RP0
$029E	$0099			MOVWF	SPBRG
$029F	$1518			BSF	TXSTA, BRGH
$02A0	$25CE			CALL	_usart_init
;DriverDeControle.pbas,50 :: 		tmpOn=50
$02A1	$3032			MOVLW	50
$02A2	$00A8			MOVWF	_tmpon
$02A3	$01A9			CLRF	_tmpon+1
;DriverDeControle.pbas,51 :: 		tmpOff=0
$02A4	$01AA			CLRF	_tmpoff
$02A5	$01AB			CLRF	_tmpoff+1
;DriverDeControle.pbas,52 :: 		s1=false
$02A6	$01A7			CLRF	_s1, 1
;DriverDeControle.pbas,54 :: 		executa:
$02A7	$	_main_executa:
;DriverDeControle.pbas,55 :: 		if Usart_Data_Ready() > 0 then
$02A7	$2604			CALL	_usart_data_ready
$02A8	$0870			MOVF	STACK_0, 0
$02A9	$3C00			SUBLW	0
$02AA	$1803			BTFSC	STATUS, C
$02AB	$2AF8			GOTO	DriverDeControle_L_13
$02AC	$	DriverDeControle_L_12:
;DriverDeControle.pbas,57 :: 		Usart_Read_Text(valorStr,"-")
$02AC	$302C			MOVLW	_valorstr
$02AD	$00BF			MOVWF	FARG_Usart_Read_Text
$02AE	$302D			MOVLW	45
$02AF	$00BC			MOVWF	?main_Local_Text+0
$02B0	$01BD			CLRF	?main_Local_Text+1
$02B1	$303C			MOVLW	?main_Local_Text
$02B2	$00C0			MOVWF	FARG_Usart_Read_Text+1
$02B3	$2440			CALL	_usart_read_text
;DriverDeControle.pbas,58 :: 		Usart_Read_Text(invert,"/")
$02B4	$3033			MOVLW	_invert
$02B5	$00BF			MOVWF	FARG_Usart_Read_Text
$02B6	$302F			MOVLW	47
$02B7	$00BC			MOVWF	?main_Local_Text+0
$02B8	$01BD			CLRF	?main_Local_Text+1
$02B9	$303C			MOVLW	?main_Local_Text
$02BA	$00C0			MOVWF	FARG_Usart_Read_Text+1
$02BB	$2440			CALL	_usart_read_text
;DriverDeControle.pbas,59 :: 		valor = StrToInt(valorStr)
$02BC	$302C			MOVLW	_valorstr
$02BD	$00BF			MOVWF	FARG_StrToInt
$02BE	$2132			CALL	_strtoint
$02BF	$0870			MOVF	STACK_0, 0
$02C0	$00BA			MOVWF	_valor
$02C1	$0871			MOVF	STACK_0+1, 0
$02C2	$00BB			MOVWF	_valor+1
;DriverDeControle.pbas,61 :: 		if strcmp(invert, "PN") = 0 then
$02C3	$3033			MOVLW	_invert
$02C4	$00BF			MOVWF	FARG_strcmp
$02C5	$3050			MOVLW	80
$02C6	$00BC			MOVWF	?main_Local_Text+0
$02C7	$304E			MOVLW	78
$02C8	$00BD			MOVWF	?main_Local_Text+1
$02C9	$01BE			CLRF	?main_Local_Text+2
$02CA	$303C			MOVLW	?main_Local_Text
$02CB	$00C0			MOVWF	FARG_strcmp+1
$02CC	$24CC			CALL	_strcmp
$02CD	$3000			MOVLW	0
$02CE	$0671			XORWF	STACK_0+1, 0
$02CF	$1D03			BTFSS	STATUS, Z
$02D0	$2AD3			GOTO	L_main_3
$02D1	$3000			MOVLW	0
$02D2	$0670			XORWF	STACK_0, 0
$02D3	$	L_main_3:
$02D3	$1D03			BTFSS	STATUS, Z
$02D4	$2AD9			GOTO	DriverDeControle_L_16
$02D5	$	DriverDeControle_L_15:
;DriverDeControle.pbas,62 :: 		s1 = true
$02D5	$30FF			MOVLW	255
$02D6	$00A7			MOVWF	_s1
;DriverDeControle.pbas,63 :: 		porta.0 = 1
$02D7	$	DriverDeControle_L_18:
$02D7	$1405			BSF	PORTA, 0
$02D8	$	DriverDeControle_L_19:
$02D8	$2ADB			GOTO	DriverDeControle_L_17
;DriverDeControle.pbas,64 :: 		else
$02D9	$	DriverDeControle_L_16:
;DriverDeControle.pbas,65 :: 		s1 = false
$02D9	$01A7			CLRF	_s1, 1
;DriverDeControle.pbas,66 :: 		porta.0 = 0
$02DA	$1005			BCF	PORTA, 0
$02DB	$	DriverDeControle_L_21:
;DriverDeControle.pbas,67 :: 		end if
$02DB	$	DriverDeControle_L_17:
;DriverDeControle.pbas,69 :: 		motor = valor div 1000
$02DB	$30E8			MOVLW	232
$02DC	$00F4			MOVWF	STACK_4
$02DD	$3003			MOVLW	3
$02DE	$00F5			MOVWF	STACK_4+1
$02DF	$083A			MOVF	_valor, 0
$02E0	$00F0			MOVWF	STACK_0
$02E1	$083B			MOVF	_valor+1, 0
$02E2	$00F1			MOVWF	STACK_0+1
$02E3	$23E6			CALL	_div_16x16_s
$02E4	$0870			MOVF	STACK_0, 0
$02E5	$00A5			MOVWF	_motor
$02E6	$0871			MOVF	STACK_0+1, 0
$02E7	$00A6			MOVWF	_motor+1
;DriverDeControle.pbas,70 :: 		ciclo = valor - (motor * 1000)
$02E8	$30E8			MOVLW	232
$02E9	$00F4			MOVWF	STACK_4
$02EA	$3003			MOVLW	3
$02EB	$00F5			MOVWF	STACK_4+1
$02EC	$2483			CALL	_mul_16x16_s
$02ED	$0870			MOVF	STACK_0, 0
$02EE	$023A			SUBWF	_valor, 0
$02EF	$00A3			MOVWF	_ciclo
$02F0	$0871			MOVF	STACK_0+1, 0
$02F1	$1C03			BTFSS	STATUS, C
$02F2	$3F01			ADDLW	1
$02F3	$023B			SUBWF	_valor+1, 0
$02F4	$00A4			MOVWF	_ciclo+1
;DriverDeControle.pbas,72 :: 		giraMotor()
$02F5	$2382			CALL	_giramotor
;DriverDeControle.pbas,74 :: 		valorStr=""
$02F6	$01AC			CLRF	_valorstr+0
;DriverDeControle.pbas,75 :: 		invert=""
$02F7	$01B3			CLRF	_invert+0
$02F8	$	DriverDeControle_L_13:
;DriverDeControle.pbas,77 :: 		end if
$02F8	$	DriverDeControle_L_14:
;DriverDeControle.pbas,79 :: 		goto executa
$02F8	$2AA7			GOTO	_main_executa
$02F9	$2AF9			GOTO	$
